### ISSUE TITLE
import 'onsen-css-components.css' lead to  input on mobile browser failed

### ISSUE THREAD

**Issue by zevenzeng** [OnsenUI/OnsenUI#2372] opened 2018-03-09 05:12 UTC
Dear OnsenUI Team,
    when i integrated  some wysiwyg components ,such as  [wangeditor](https://github.com/wangfupeng1988/wangEditor/) ,[summernote](https://github.com/summernote/summernote), it can perform well on pc browser,but not on mobile browser. on the  mobile browser ,it can not  input on these wysiwyg components.

    after many test,i found the reason is 'onsenui/css/onsen-css-components.css'. when import this file, the question is appears. i can't fixed this  problem.
thank you.

**Comment by asialgearoid** [comment] 2018-03-22 02:12
@zevenzeng Could you provide a bit more information on what your issue is? If possible, please try to reproduce it as outlined in the issue template.

> 1. Go to https://tutorial.onsen.io/
> 2. Select a framework and a template
> 3. Modify the template until the issue is visible
> 4. Hit "Report an issue" button to open Github issue page. You need to be logged in on Github.
> 
> This uses the latest release of Onsen UI. In case the issue is not reproducible in desktop browsers, just follow the previous steps and also modify the platform version at the end (you can also open the mentioned site on a device).

**Comment by asialgearoid** [comment] 2018-05-01 00:09
I am closing this issue due to a lack of a reply.

**Closed by asialgearoid** 2018-05-01 00:09 UTC
Labels: awaiting reply
