### ISSUE TITLE
React: Create TabPage cause an exception wit ForwardRef

### ISSUE THREAD

**Issue by vit1251** [OnsenUI/OnsenUI#2976] opened 2022-06-07 23:36 UTC
Create `Page` with `TabPage` and catch an exception:

Source code:
```
  const renderTabs = (activeIndex, tabbar) => {
      const items = [];
      return [
        {
          content: (<TabPage title="Home" active={activeIndex === 0} />),
          tab: (<Tab label="Home" icon="md-home" />),
        },
        {
          content: (<TabPage title="Settings" active={activeIndex === 1} />),
          tab: (<Tab label="Settings" icon="md-settings" />),
        }
      ];
  };

  return (
    <>

      <Page>
            <Button onClick={handleClick}>Tap me!</Button>

            <Tabbar position="bottom"
                    activeIndex={pageIndex}
                    renderTabs={renderTabs}
                    />

      </Page>

    </>
  );
```

Exception:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef`.
```

**Comment by emccorson** [comment] 2022-06-07 23:43
Thank you for the report. Could please also let us know the versions of
onsenui and vue-onsenui?

**Comment by vit1251** [comment] 2022-06-07 23:54
> Could please also let us know the versions of onsenui and react-onsenui?

const [onsenui, react-onsenui ] = [ 2.12.0, 1.12.0 ];

=)

**Comment by emccorson** [comment] 2022-06-08 02:14
I tried to reproduce the problem but I was unable to do so with the code provided.

Can you have a look at https://github.com/OnsenUI/OnsenUI/blob/45b036e25eea02ef9b4af59d1c9e783bc312e7a7/react-onsenui-examples/src/components/Tabbar.js ? It does basically the same as your code and it is working correctly. That might show where the problem is.

**Comment by emccorson** [comment] 2022-09-14 07:00
Closing as can't reproduce.

**Closed by emccorson** 2022-09-14 07:00 UTC
