### ISSUE TITLE
ons-tabbar inserts duplicated pages on iOS / mobile Safari

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1584] opened 2016-09-14 08:44 UTC
Reported by @iqmeta in #1580.

> Also there is a new **tab-bar problem with iOS / mobile Safari,** on Chrome it's working fine:
> 
> ```
> document.addEventListener('init', function (event)
> {
> 	var page = event.target;   
> 	console.log("init:" + page.id);
> }
> ```
> 
> 
> **Chrome console is correct:**
> ```
> init:tabBar
> init:menu
> init:gruppenPage
> init:home
> ```
> 
> **On iOS gruppePage is added 3x times:**
> ```
> init:menu
> init:gruppenPage
> init:gruppenPage
> init:gruppenPage
> init:home
> ```
> 
> **Markup Tabbar** no where else in code gruppen.html was referenced
> ```
>  <ons-tabbar id="tabs" animation="slide">
>         <ons-tab active page="home.html" id="alarm">
>             <div class="tab-bar__icon">
>                 <ons-icon icon="ion-ios-bell" size="33px" style="line-height:0px"></ons-icon>
>             </div>
>         </ons-tab>
>         <ons-tab id="gruppen" page="gruppen.html">
>             <div class="tab-bar__icon">
>                 <ons-icon icon="ion-radio-waves" size="33px" style="line-height:0px"></ons-icon>
>             </div>
>         </ons-tab>
> </ons-tabbar>
> ```
> **gruppen.html**
> ```
> <ons-page id="gruppenPage">
>     <div id="testX">X</div>
>     <ons-list id="groupList">
>     </ons-list>
> </ons-page>
> ```
> 
> ```
> tabs.addEventListener('postchange', function(event)
> {
> 	$("#textX").text("Y") <= works only on chrome. on iOS not! because tabBar added 3 times the gruppenPage.html. Th
> }
> 
> ```
> 
> **Screenshot from Cordova Remote Debugger**
> ![image](https://cloud.githubusercontent.com/assets/7533842/18483683/67da9054-79e5-11e6-86d9-a00c98e6dcf8.png)
> 
> 
> 
> Going back to R17 for now. There this works flawless ;-) Hope this helps a bit. Great work on onsen by the way :+1: .
> 
> 
> Update:
> With R17 i have double inits with splitter too:
> ![image](https://cloud.githubusercontent.com/assets/7533842/18491964/435e4ad0-7a09-11e6-8133-bd3ee42133d6.png)
> 
> think these are back or still present:
> 
> https://community.onsen.io/topic/605/init-called-twice-on-one-page-after-updating-to-rc16/
> 
> https://github.com/OnsenUI/OnsenUI/issues/1400
> 
> 
> 
> 
> 
>

**Comment by frankdiox** [comment] 2016-09-14 08:50
@asial-matagawa The link to the community was a different issue and it was fixed in https://github.com/OnsenUI/OnsenUI/pull/1540

**Comment by asial-matagawa** [comment] 2016-09-14 08:57
@frankdiox Thank you for information!

**Comment by argelius** [comment] 2016-09-14 12:27
Thank you @asial-matagawa !

Do you have time to look at this issue tomorrow?

**Comment by asial-matagawa** [comment] 2016-09-14 13:57
@argelius No problem. I will check this soon.

**Comment by argelius** [comment] 2016-09-14 13:57
@asial-matagawa Thank you! :+1:

**Comment by asial-matagawa** [comment] 2016-09-15 09:17
@andreas: @frankdiox: @anatoo:
It seems that Custom Elements v1 polyfill calls `connectedCallback` many times per one `ons-tab` element on macOS Safari (on Chrome it does not).
At this time I have yet to identified that which of the polyfill and Onsen UI core causes this issue.

**Comment by asial-matagawa** [comment] 2016-09-15 11:31
As a test I disabled Custom Elements v0 implementation (included in Chrome 52) which [document-register-element](https://github.com/WebReflection/document-register-element) uses internally, then Chrome 52 also reproduced the problem.
So we can conclude that this is not a problem of Safari.

**Comment by argelius** [comment] 2016-09-15 11:33
@asial-matagawa Thanks! So it looks like it's a bug in the polyfill

I can also take a look at this tomorrow since it's reproducible in Chrome

**Comment by argelius** [comment] 2016-09-15 11:33
Maybe we can make a patch for the polyfill, I think that's better than trying to patch the problem in Onsen UI

**Comment by asial-matagawa** [comment] 2016-09-16 02:16
@argelius:
How to reproduce it on Chrome 52:

1. Create an empty directory.
2. Copy 5 files from [a Gist](https://gist.github.com/asial-matagawa/01cc32086e3cd6b6a51d01f4e296c6ab) I have created.
3. Run `git clone https://github.com/OnsenUI/OnsenUI --branch 2.0.0-rc.18 --depth 1` in the directory.
4. Run `npm install` in `OnsenUI` directory.
5. Rewrite `if (!(REGISTER_ELEMENT in document))` in `OnsenUI/core/vendor/document-register-element.max.js` to `if (true)`.
6. Run `gulp core` in `OnsenUI` directory.
7. Open `index.html` on Chrome 52 through a local HTTP server launched by something like `webpack-dev-server`.

**Comment by asial-matagawa** [comment] 2016-09-27 11:40
@anatoo @argelius @frankdiox
I have identified the cause of this issue.
It consists of two factors:

1. Custom Elements v0 implementation in Chrome 52 does not call `disconnectedCallback` in `_compile` of Onsen UI component, but [document-register-element](https://github.com/WebReflection/document-register-element) does.
2. Our implementation of `disconnectedCallback` in `ons-tab.js` does not consider that when `disconnectedCallback` is called right after `connectedCallback`, `disconnectedCallback` needs to cancel XHR sent by `connectedCallback`. 

Here is an execution log of the example code running with [document-register-element](https://github.com/WebReflection/document-register-element).
```
ons-tab[alarm] - init
ons-tab[alarm] - connectedCallback
ons-tab[alarm] - connectedCallback - contentReady
ons-tab[gruppen] - init
ons-tab[gruppen] - connectedCallback
ons-tab[gruppen] - connectedCallback - contentReady
ons-tab[gruppen] - connectedCallback - contentReady - onReady
ons-tab[gruppen] - _loadPageElement
ons-tab[alarm] - disconnectedCallback
ons-tab[gruppen] - disconnectedCallback
ons-tab[alarm] - connectedCallback
ons-tab[alarm] - connectedCallback - contentReady
ons-tab[gruppen] - connectedCallback
ons-tab[gruppen] - connectedCallback - contentReady
ons-tab[gruppen] - connectedCallback - contentReady - onReady
ons-tab[gruppen] - _loadPageElement
ons-tab[alarm] - disconnectedCallback
ons-tab[gruppen] - disconnectedCallback
ons-tab[alarm] - connectedCallback
ons-tab[alarm] - connectedCallback - contentReady
ons-tab[gruppen] - connectedCallback
ons-tab[gruppen] - connectedCallback - contentReady
ons-tab[gruppen] - connectedCallback - contentReady - onReady
ons-tab[gruppen] - _loadPageElement
ons-tab[alarm] - _loadPageElement
ons-tab[gruppen] - connectedCallback - contentReady - onReady - page loaded
appendChild
ons-tab[gruppen] - connectedCallback - contentReady - onReady - page loaded
appendChild
ons-tab[gruppen] - connectedCallback - contentReady - onReady - page loaded
appendChild
```

So we have to fix:
1. [document-register-element](https://github.com/WebReflection/document-register-element)
2. Our implementation of `disconnectedCallback` in `ons-tab.js`

At this moment I don't have a good idea.
I will try to fix this later, but it might be quite difficult for me.

**Comment by nodefish** [comment] 2016-09-29 12:30
Thanks for finding this, I've had a similar issue with init firing many times but I didn't manage to isolate it, and assumed it was a coding error from my side. This fix will be a big deal for my app. 👍

**Comment by argelius** [comment] 2016-10-19 09:59
This has been fixed now.

**Closed by argelius** 2016-10-19 09:59 UTC
Labels: bug

**Comment by nodefish** [comment] 2016-10-19 10:03
Awesome! Which build has this fix?

**Comment by argelius** [comment] 2016-10-19 10:07
@nodefish We are aiming to release on Friday this week. You can build from source manually if you want to use it right now.

**Comment by nodefish** [comment] 2016-10-19 10:07
Thanks 👍

**Comment by iqmeta** [comment] 2016-10-19 13:13
Perfect. Thanks a lot... 👍
