### ISSUE TITLE
ons-speed-dial - Issues with position fixed & scrolling on iOS

### ISSUE THREAD

**Issue by alegauss** [OnsenUI/OnsenUI#1448] opened 2016-06-09 01:14 UTC
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 rc 9
Angular 1.5.2
iOS 9.2

__Encountered problem__

IOS have a weird behavior with a fixed object on a div with scroll, because the object does not keep fixed.

__How to reproduce__
I had a problem using ons-speed-dial with ons-list and I solved the problem changing the css fab, inserting -webkit-transform: translateZ(0), for example:

```
.fab--bottom__right {
  top: auto;
  bottom: 20px;
  right: 20px;
  left: auto;
  position: fixed;
  -webkit-transform: translateZ(0);
}
```

**Comment by IliaSky** [comment] 2016-06-10 02:54
Thank you for the bug report. While this may be a duplicate of #1290 the fix which you are proposing is definitely something worth checking out. ^_^

**Comment by IliaSky** [comment] 2016-07-07 04:52
Unfortunately after some testing the suggested fix seems to produce buggy results for me. Maybe your devices are better than the ones which I used.  

I guess if your fix works for you that's fine, but for now I will close this - we will come up with another fix for the core.

**Closed by IliaSky** 2016-07-07 04:52 UTC
