### ISSUE TITLE
Ons-range not working on angular 2 ?

### ISSUE THREAD

**Issue by gotenxds** [OnsenUI/OnsenUI#1607] opened 2016-09-29 13:43 UTC
Hi, I recently upgraded my app to onesn-angular 1.0.0.rc-1 ( from 0.1.0-beta.9)
and to  onsen 2.0.0 (from 2.0.0-rc.17)

And now I get an error when changing moving an ons-range in my app.

I tried this in a clean page with no js interaction so the html looks like so:

`<ons-range></ons-range>`

And I still get the following error: 

![image](https://cloud.githubusercontent.com/assets/3519520/18956339/c83d7a4e-8663-11e6-8eec-6fec31d4bc4f.png)

**Comment by gotenxds** [comment] 2016-09-29 14:19
Hi, did a bit of digging, apperantly this happens only when I use chrome debug on IOS mode, I looked up in your code and I found this section:

`
		// Issue #160: on iOS 7, some input elements (e.g. date datetime month) throw a vague TypeError on setSelectionRange. These elements don't have an integer value for the selectionStart and selectionEnd properties, but unfortunately that can't be used for detection because accessing the properties also throws a TypeError. Just check the type instead. Filed as Apple bug #15122724.
		if (deviceIsIOS && targetElement.setSelectionRange && targetElement.type.indexOf('date') !== 0 && targetElement.type !== 'time' && targetElement.type !== 'month') {
			length = targetElement.value.length;
			targetElement.setSelectionRange(length, length);
		} else {
			targetElement.focus();
		}
	};
`
This explains it, not sure what the correct behavior should be tough.

Also from MDN:

`
Note that accordingly to the WHATWG forms spec selectionStart, selectionEnd properties and setSelectionRange method apply only to inputs of types text, search, URL, tel and password. Chrome, starting from version 33, throws an exception while accessing those properties and method on the rest of input types.
`

**Comment by argelius** [comment] 2016-10-21 04:03
@gotenxds I will close this since it seems like it's only an issue in the Chrome DevTools.

Also, I am unable to reproduce it in Chrome myself.

**Closed by argelius** 2016-10-21 04:03 UTC
Labels: angular2
