### ISSUE TITLE
Tabbar checkbox label issue

### ISSUE THREAD

**Issue by davidhealey** [OnsenUI/OnsenUI#2604] opened 2018-12-28 22:01 UTC
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Ubuntu 64-bit

[Browser]
  Desktop - Firefox 64.0 on Ubuntu 64-bit
```

__Encountered problem__
I have a page with a tabbar inside a navigator, there are 2 tabs (A, B). On tab B there is a button, when clicking this button a new page is pushed in the navigator which also has a button. Clicking this final button shows the page of tab A, by itself without the tabbar.

Now here's the weird part, tab A has a list of checkboxes encased in labels (so clicking the label will check its box) this works fine when I go to tab A via the tabbar page, but when I open it by clicking the button on the tab B sub-page it doesn't work. I can click the label and the event fires but the checkbox doesn't get checked, I can click the checkbox directly though to check it.

I discovered that if I remove the original tabbar page (index 0) from the page stack then the checkboxes work but I can no longer use the back button on my sub-page so that's no good.

__How to reproduce__
 Click to the second tab, push the button, push the next button, then try to check a box by clicking a label (it won't work).

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
        <ons-navigator id="nav">
          <ons-page>
            <ons-toolbar>
              <div class="center"></div>
            </ons-toolbar>

            <ons-tabbar>
              <ons-tab page="page1.html" label="Tab 1" icon="ion-home, material:md-home" badge="7" active>
              </ons-tab>
              <ons-tab page="page2.html" label="Tab 2" icon="md-settings" active-icon="md-face">
              </ons-tab>
            </ons-tabbar>
          </ons-page>
        </ons-navigator>

        <template id="page1.html">
          <ons-page id="page1">
            <p>This is the first page.</p>
            <ons-list>
              <ons-list-item tappable>
                <label class="left">
                  <ons-checkbox input-id="check-1"></ons-checkbox>
                </label>
                <label for="check-1" class="center">
                  Apple
                </label>
              </ons-list-item>
              <ons-list-item tappable>
                <label class="left">
                  <ons-checkbox input-id="check-2"></ons-checkbox>
                </label>
                <label for="check-2" class="center">
                  Banana
                </label>
              </ons-list-item>
            </ons-list>
          </ons-page>
        </template>

        <template id="page2.html">
          <ons-page id="page2">
            <p>This is the second page.</p>
            <ons-button id="push-button" onclick="nav.pushPage('page3.html');">Push Me</ons-button>
          </ons-page>
        </template>

        <template id="page3.html">
          <ons-page id="page3">
            <p>This is the third page.</p>
            <ons-button id="push-button" onclick="nav.pushPage('page1.html');">Push Me Too</ons-button>
          </ons-page>
        </template>
```

- __JS__

```javascript
document.addEventListener('init', function(event) {
  var nav = document.getElementById('nav');
});
```

**Comment by emccorson** [comment] 2018-12-29 09:31
@davidhealey Thanks for this detailed bug report!

I haven't investigated this fully yet, but it looks like the bug can be reproduced without page 3 i.e. by making the first button point towards `page1.html` instead of going to `page3.html`.

My guess is that the problem is caused by `pushPage` not checking if the page that's being pushed is already in the page stack.

**Comment by davidhealey** [comment] 2018-12-29 12:09
Thanks for confirming. Interesting to know the problem is there without the extra page - I built this as a minimal example from a larger project I'm working on where I first noticed the bug, but didn't think to try it with just two pages.

**Comment by emccorson** [comment] 2019-01-09 21:21
Reopening because #2611 doesn't actually fix the issue at all :man_facepalming:

It actually fixes the related issue of the checkbox not keeping its checked value when you push another page and then re-show the tabbar page using `bringPageTop`.

Full example:

JS:
```javascript
document.addEventListener('init', function(event) {
  var nav = document.getElementById('nav');
});
```

HTML:
```html
<ons-navigator id="nav" page="tabbar-page.html"></ons-navigator>

<template id="tabbar-page.html">
  <ons-page>
    <ons-tabbar>
      <ons-tab page="tab.html" label="tab"></ons-tab>
    </ons-tabbar>
  </ons-page>
</template>

<template id="tab.html">
  <ons-page>
    <ons-checkbox input-id="checkbox"></ons-checkbox>
    <label for="checkbox">Banana</label>
    
    <ons-button onclick="nav.bringPageTop('next-page.html')">Next page</ons-button>
  </ons-page>
</template>

<template id="next-page.html">
  <ons-page>
    <ons-button onclick="nav.bringPageTop('tabbar-page.html')">Tabbar page</ons-button>
  </ons-page>
</template>
``` 

@davidhealey By the way, once the fix is in, your code should use `ons-navigator.bringPageTop` instead of `ons-navigator.pushPage`. `bringPageTop` only creates a new page if it doesn't already exist in the page stack; `pushPage` always pushes a new page. So since you want to reshow a page, you will need to use `bringPageTop`.

**Comment by davidhealey** [comment] 2019-01-09 21:51
Ok that's good to know, thanks

**Comment by davidhealey** [comment] 2019-03-02 02:20
> @davidhealey By the way, once the fix is in, your code should use `ons-navigator.bringPageTop` instead of `ons-navigator.pushPage`. `bringPageTop` only creates a new page if it doesn't already exist in the page stack; `pushPage` always pushes a new page. So since you want to reshow a page, you will need to use `bringPageTop`.

What's preventing bringPageTop working currently? I just tried it in the demo but no luck, although I see it is in the ons-navigator documentation.

**Comment by davidhealey** [comment] 2019-04-04 21:49
Bump bump

**Comment by emccorson** [comment] 2019-07-16 14:11
Sorry for the delay @davidhealey 

I've been trying to think through this issue and I think it's going to be more trouble than it's worth to link the navigator and tabbar page stacks, which is what would be required for a full fix. Actually, it's not clear that we should even consider a page that is in both the navigator and tabbar stacks to be the same page. It looks like the sort of problem where we could put in a fix and it would cause unforeseen headaches in the future.

As a workaround, I'd suggest changing your code for the third button to go to the tabbar page instead and hide the tabbar. Effectively that shows just the tab page since the user can't see or interact with the tabbar.

**Closed by emccorson** 2019-07-16 14:11 UTC
Labels: bug, core
