### ISSUE TITLE
Carousel auto-scroll-ratio only works in one direction

### ISSUE THREAD

**Issue by mittermayr** [OnsenUI/OnsenUI#2687] opened 2019-08-29 08:55 UTC
__Environment__
Onsen UI Version:
any

Framework:
React (but same for others)

Framework binding:
React (but any)

Additional libraries:
-

Platform:
Cordova 8, iOS

__Encountered problem__

The auto-scroll (set to true, and values anything between 0 and 1) works perfectly fine when dragging the carousel to the left (standard use). 

It does NOT work correctly when dragged back (from left to right), where the auto-scroll still only activates looking at the offset from the left, and not from the right side of the screen (which it should).

__How to reproduce__
Have three carousel items, or enough to exceed the screen width. Set `auto-scroll` to true, and `auto-scroll-ratio` to a value like `0.1` to test it. Advancing forward (to further items, i.e. dragging from right to left) works perfectly and it automatically snaps. Dragging the other way back requires a lot of dragging (0.9 instead of 0.1 now!) to make the snap work.

**Comment by emccorson** [comment] 2020-09-07 20:05
I'm not able to replicate this one. I tested both `auto-scroll-ratio` at `0.9` and `0.1` for plain JS and React and everything seems to be working fine.

I'll close this for now. If someone can provide a sample to reproduce the problem I'll reopen.

**Closed by emccorson** 2020-09-07 20:05 UTC
Labels: @REPRODUCE
