### ISSUE TITLE
Popover error "Capturing backbutton-handler is failure"

### ISSUE THREAD

**Issue by leomontenegro6** [OnsenUI/OnsenUI#2733] opened 2020-03-12 13:23 UTC
Probably a duplicate of #1119

I'm using Onsen UI v2.10.10 together with jQuery v3.1.1. Tried lots of components (menu, alert dialogs and modals), and most of them are very good and works fine on most cases.

However, I'm trying to use Popover component in order to show a message below a button when user clicks it, and I'm getting issues when pressing the physical Back button on my device. If a popover is opened, whenever I press back button, this error shows up on the console:

```
Uncaught Error: Capturing backbutton-handler is failure.
    at onsenui.min.js:2
    at Array.reduce (<anonymous>)
    at e (onsenui.min.js:2)
    at t.value (onsenui.min.js:2)
    at t.value (onsenui.min.js:2)
    at t.value (onsenui.min.js:2)
    at Channel.fire (cordova.js:843)
    at cordova.js:229
```

Initially, I tried adding "cancelable" attribute, that supposedly makes the popover disappear when user presses Back button or clicks outside the popover. Clicking outside the popover works as expected, but when Back button is pressed, the error above shows up.

I also tried removing the "cancelable" attribute and tried pressing Back button to see what happens. The result was the same error above being shown on the console, and the "navigator.goBack()" action, that should've been executed, didn't happened.

A simple workaround for that is using "alert-dialog" component as a replacement, and do all needed style changes in order to make it more similar to a popover. But is there another way to make popover component work as expected?

**Comment by emccorson** [comment] 2020-09-07 20:15
I'm not able to reproduce this bug. I tried added `cancelable` to the [popover playground example](https://onsen.io/playground/?framework=vanilla&category=reference&module=popover) and the device back button closed the popover without error.

If someone can provide a sample that shows the problem I'll reopen this, but closing for now.

**Closed by emccorson** 2020-09-07 20:15 UTC
