### ISSUE TITLE
Navigator re-mounts entire component stack every time a page is pushed 

### ISSUE THREAD

**Issue by ggaabe** [OnsenUI/OnsenUI#2667] opened 2019-07-09 19:24 UTC
__Environment__

Onsen UI Version:
2.9.2 
- 

Framework:
React 16.8.1
- 

Framework binding:

- 

Additional libraries:

- 

Platform:
Chrome
- 

__Encountered problem__
Whenever a page is pushed or popped from the Navigator's stack, every single component on the stack remounts (this also means components lose their data when returning to them, if data is loaded in componentDidMount)

__How to reproduce__
Push two pages onto the navigator's stack. Put a console.log in each component's componentDidMountMethod, start a navigator out with one page, then push the second page onto the stack, and check the console. Then pop the second page and check the console again.

**Comment by emccorson** [comment] 2022-04-06 22:48
I was not able to reproduce the behaviour reported.

Using the following code:
```js
class One extends React.Component {
  componentDidMount() {
    console.log('one mounted');
  }

  render() {
    return (
      <Page>
        <Button onClick={() => this.props.navigator.pushPage({component: Two})}>push</Button>
      </Page>
    );
  }
}

class Two extends React.Component {
  componentDidMount() {
    console.log('two mounted');
  }

  render() {
    return (
      <Page>
        <Button onClick={() => this.props.navigator.popPage()}>pop</Button>
      </Page>
    );
  }
}

class App extends React.Component {
  renderPage(route, navigator) {
    const props = route.props || {};
    props.navigator = navigator;

    return React.createElement(route.component, props);
  }

  render() {
    return (
      <Navigator
        renderPage={this.renderPage}
        initialRoute={{component: One}}
      />
    );
  }
}
```

`'one mounted'` is logged once, and `'two mounted'` is logged every time the second page is pushed, as expected.

To avoid the second page mounting every time, you should be able to use `bringPageTop` but I'm not sure that has been implemented for React yet. I will investigate this.

In the meantime, I will close this as not reproducible. If I have missed something, please let me know and I will reopen the issue.

**Closed by emccorson** 2022-04-06 22:48 UTC
Labels: @REPRODUCE
