### ISSUE TITLE
 Exception when clicking on the back button of a page containing a floating action button

### ISSUE THREAD

**Issue by jakwarrior** [OnsenUI/OnsenUI#1508] opened 2016-07-12 09:19 UTC
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 RC 15
Angular 1.5.5
Chrome 51

__Encountered problem__
When I click on the back button of a page which contains a floating action button, an exception occured 
```
TypeError: this.emit is not a function
   at Class._destroy (VM259 angular-onsenui.js:721)
   at Scope.$broadcast (VM254 angular.js:17552)
   at Scope.$destroy (VM254 angular.js:17170)
   at Class._onPostpop (VM259 angular-onsenui.js:1446)
   at defaultHandlerWrapper (VM254 angular.js:3456)
   at ons-navigator.eventHandler (VM254 angular.js:3444)
   at Object.util.triggerElementEvent (VM127 onsenui.js:3992)
   at VM127 onsenui.js:16388
```

__How to reproduce__
Go to [https://codepen.io/anon/pen/AXbXEp](https://codepen.io/anon/pen/AXbXEp), click on the "push page" button then on the return button => look at the console to see the stack trace

**Comment by IliaSky** [comment] 2016-07-12 09:29
Duplicate of #1496. This has already been fixed. The fix will be available when we release RC.16.

**Closed by IliaSky** 2016-07-12 09:29 UTC
