### ISSUE TITLE
The ons-page set on ons-tabbar is called twice in the init event.

### ISSUE THREAD

**Issue by keijiodagawa** [OnsenUI/OnsenUI#1715] opened 2016-11-27 22:17 UTC
__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 1.5.8

[Platform]
    Mobile - Android
    Mobile - iOS
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 54.0.2840.99
    Desktop - Safari 10.0.1
```

__Encountered problem__
The ons-page set on ons-tabbar is called twice in the init event.
I want to work the init event of ons-page set on ons-tabbar only once.

__How to reproduce__

https://codepen.io/keiji/pen/MbvPvx

```
<ons-tabbar>
  <ons-tab page="tab1.html" active>
  </ons-tab>
  <ons-tab page="tab2.html">
  </ons-tab>
</ons-tabbar>

<ons-template id="tab1.html">
  <ons-page id="page1">
  </ons-page>
</ons-template>

<ons-template id="tab2.html">
  <ons-page id="page2">
  </ons-page>
</ons-template>

ons.bootstrap();
document.addEventListener('init', function(event) {
  alert(event.target.id);
}, false);
```

**Comment by frankdiox** [comment] 2016-11-30 04:47
@keijiodagawa I can reproduce it in 2.0.4 but looks like it's already fixed in 2.0.5 (master branch right now). We will try to release soon.

**Closed by frankdiox** 2016-11-30 04:47 UTC
Labels: angular1
