### ISSUE TITLE
Open sliding menu should not propagate any events to open page

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#319] opened 2014-11-13 06:12 UTC
Hi @argelius,

when sliding menu is open, no scroll, no touch etc should be propagated to the page when menu < 100%. This should be like the native behavior. If you don't want to block this automatically maybe you could provide a lockPage() method, so that no events (even scroll) be triggered. To demonstrate my problem, I want to share this video with you. As you can see, I have some touch move ng-slide-left actions on the page which will block and stop the sliding menu from closing properly when I drag in the page frame. 

http://youtu.be/bDoW4q-2Zs0

Hope you get my point.

Regards
Hirbod

**Comment by Hirbod** [comment] 2015-01-23 20:58
Dear @argelius 
as far as I can see, this only fix click-events - but will not behave like native behavior (closing the menu when click on the page)

Would you please integrate this also?

**Comment by Hirbod** [comment] 2015-01-23 21:00
And your fix will also do something real bad: 
![bildschirmfoto 2015-01-23 um 21 59 55](https://cloud.githubusercontent.com/assets/504909/5882591/2d89bcee-a34b-11e4-8a38-ae41468e26e7.png)

it will break the nav-icon at the right side. With your pointer-events none, you have to activate click on page to close the menu

**Comment by Hirbod** [comment] 2015-01-23 22:52
I'm sorry... as I can see you already did that and even changed to hammer instead of click. Very nice. Will try right now and give you some feedback, if you don't mind :)

**Comment by Hirbod** [comment] 2015-01-23 23:09
@argelius 

Sorry for the spam, just installed the dev - and everything is really broken.
The first time, everything works well. But after the menu was open, I can't click ANYTHING more. It's only possible to open menu with sliding, cant even click any button inside the page. Something seem to break all the pointer events. 

http://youtu.be/HXOa7FFd_1U

**Comment by argelius** [comment] 2015-01-26 03:45
Thanks for testing the dev-branch @Hirbod, it's really appreciated! :)

I'll take a look at this.

**Comment by argelius** [comment] 2015-01-30 02:55
Sorry for breaking this. Fixed in: https://github.com/OnsenUI/OnsenUI/commit/ccee88439556985fda8acb25c506d8b25dabc51e

The current behavior is that it will close when tapping outside the open menu as well as blocking pointer events on the main page while the menu is open.

@Hirbod Feel free to confirm this behavior.

**Comment by Hirbod** [comment] 2015-01-30 02:58
@argelius 
Thank you, I'll try right now. Any chances 1.2.2 going live these days? Want to push my in the appstore in 2-3 days.

**Comment by argelius** [comment] 2015-01-30 03:03
Sorry, we have not decided on a date. However, I can safely say it won't be released in the next few days. If I would hazard a guess I think it will be done in around two weeks from now.

However, if you think the `master` branch is stable enough and you feel brave enough you can use that :)
If you find anything else that's broken in the master branch I'll try to fix it as soon as possible, the master branch is supposed to be quite stable.

**Comment by Hirbod** [comment] 2015-01-30 03:03
@argelius can confirm it fixed the bug. Works like charm. But broke ons-row align="center"

![bildschirmfoto 2015-01-30 um 04 03 07](https://cloud.githubusercontent.com/assets/504909/5970544/ff1ef326-a834-11e4-878d-bf2d9c072d5a.png)

**Comment by Hirbod** [comment] 2015-01-30 03:10
And I found another sliding menu bug. If I call a resetToPage or another page which also includes the menu button, if opens and closes immediately.

Like the events where doubled.

**Comment by Hirbod** [comment] 2015-01-30 03:13
Here, the demo:
https://www.youtube.com/watch?v=KZGvqjERybY&feature=youtu.be

**Comment by argelius** [comment] 2015-01-30 03:37
I made an example but couldn't reproduce the bug with `resetToPage()`. What's your structure? Do you have a navigator on the main page of the sliding menu where you do `resetToPage()` ?

`<ons-rol align="center">` hasn't been changed so I don't think it's related.

**Comment by Hirbod** [comment] 2015-01-30 03:38
align="center" is related. I've reverted the master and everything is fine now.

I only have a navigator created in DOM once I launch the app (home.html, which resetToPage to home2.html). home.html will never be called again.

**Comment by argelius** [comment] 2015-01-30 03:44
Run

```bash
gulp build
```
in `css-components` directory and then in project root.

**Comment by Hirbod** [comment] 2015-01-30 03:45
I did all the steps 1:1 as mentioned on the Wiki

**Comment by argelius** [comment] 2015-01-30 03:56
I see, that's really strange. Is this behavior only present on iOS or does it happen if you run in a browser as well?

I can't reproduce this. Do you have any idea what might trigger it? I've tried with a navigator as you said but with no issues.

**Comment by Hirbod** [comment] 2015-01-30 03:57
I'd never tried in a browser, as it is not possible due to my native plugins. Just tried on iOS Device and Simulator.

**Comment by Hirbod** [comment] 2015-01-30 04:19
Actually, this is something logic. I have a click-event on it. And you also listen to a tab. I call my click and with some delay, Hammer.js calls back. I guess - at least currently - the only way to fix this would be to remove the onclick from my menu-icon

**Comment by Hirbod** [comment] 2015-01-30 04:23
Ok, I can reprodue this bug right now. I have a Macbook. When I make a "tab" on my Touchpad, it will make this kind of double stuff. But when I really click the button with the mouse, this bug does not occur.

**Comment by Hirbod** [comment] 2015-01-30 04:26
Watch out for the callout / opacity on the button. (cause video has no sound)
At the moment, you see the opacity beeing reduced, I did a real click, before, just tabbed on the touchpad.

https://www.youtube.com/watch?v=fsxUAy6ft0M&feature=youtu.be

**Comment by argelius** [comment] 2015-01-30 04:58
I see, seems it triggers the tap event when you click that button. 

Changed the implementation a bit so it removes the tap handler when the menu is closed and binds it after it's been opened. This should be safe.

https://github.com/OnsenUI/OnsenUI/commit/b42b8a17ed1d44ba87f14aebf0606c7d0d9fb08e

Does this fix it for you? All my examples work fine after this change.

**Comment by Hirbod** [comment] 2015-01-30 22:11
Hi @argelius 

thank you very much! Bug is fixed. Works well!

**Comment by eecsxielu** [comment] 2015-01-31 00:05
Hi @argelius 

Thank you for your efforts! To fully imitate native behavior, I believe sliding should also be disabled on main page when menu page is open.

Additionally, It is not a good experience when you scroll down your main page and at the same time you can open your menu just because you're not sliding directly down but to the bottom right direction.

**Comment by Hirbod** [comment] 2015-01-31 00:07
I disagree. Sliding (to close the menu) should work as it do right now, even when the menu is open.
But I do agree with the second argument of @eecsxielu

**Comment by eecsxielu** [comment] 2015-01-31 00:11
Yeah, you can definitely slide to close the menu but you should not be able to scroll the content on your main page. If you have Gmail app installed, you can verify that you can do nothing on the main page except that you can slide to close the menu. In other words, the main page should be fully locked down.

**Comment by Hirbod** [comment] 2015-01-31 00:12
Ok @eecsxielu , now I understand. You're totally right. Slide down/up should be blocked, slide-left/slide-sright should be able. You're right, sorry!

**Closed** 2015-02-09 09:44 UTC
Labels: bug

**Comment by Hirbod** [comment] 2015-02-09 09:52
@argelius
What about the scroll issue? No statement ?

**Comment by argelius** [comment] 2015-02-09 10:02
Sorry, I didn't forget about it. :)

Will look at this as well but I think the fix is similar to the one for https://github.com/OnsenUI/OnsenUI/issues/422 so I'll do those together.
