### ISSUE TITLE
onsen 2.9.2 v-ons-navigator animationOptions Invalid configuration ？

### ISSUE THREAD

**Issue by moonlitnighta** [OnsenUI/OnsenUI#2398] opened 2018-04-14 03:29 UTC
![image](https://user-images.githubusercontent.com/22231630/38763830-998168cc-3fd6-11e8-8351-f479705fb756.png)
![image](https://user-images.githubusercontent.com/22231630/38763833-a1446bc2-3fd6-11e8-9017-be9ba9e29358.png)
![image](https://user-images.githubusercontent.com/22231630/38763838-a9b6250c-3fd6-11e8-92db-c13e643fd6d5.png)

package:
![image](https://user-images.githubusercontent.com/22231630/38763869-434ccb08-3fd7-11e8-9cc8-7b646b32d76e.png)

'duration' and 'delay' have no effect in 'animationOptions'. 
But the 'animation' option has an effect

**Comment by asialgearoid** [comment] 2018-04-17 02:06
It looks like you may be using the wrong key for setting the options. In your third screenshot, you should use `onsNavigatorOptions`, not `options`.

Below is an example of how you might push a new page:
```
this.$emit('push-page', {
  ...page2,
  onsNavigatorOptions: {
    animation: 'lift',
    animationOptions: { duration: .5 }
  }
});
```

**Comment by moonlitnighta** [comment] 2018-04-17 06:58
@asialgearoid 
I pushed the page like this :
![image](https://user-images.githubusercontent.com/22231630/38853022-8ba2805e-424e-11e8-8afe-174e5264f1c0.png)

In the figure, if I replace 'options' with 'onsNavigatorOptions', it still seems to have no effect 0-0, and 'animation: 'fade'' is also invalid.
I've been using 'options' before, and it works fine and I updated the 2.9.2 version later. It is invalid, but ’animation’ is still valid

**Comment by asialgearoid** [comment] 2018-04-22 23:33
@moonlitnighta Hmm. Could you reproduce it on the [Onsen UI Playground](https://onsen.io/playground)?

**Comment by asialgearoid** [comment] 2018-05-23 01:38
Closing due to lack of a reply. Please re-open if this is still an issue.

**Closed by asialgearoid** 2018-05-23 01:38 UTC
Labels: vue
