### ISSUE TITLE
toast don't work in `1.11.4`

### ISSUE THREAD

**Issue by DerGoogler** [OnsenUI/OnsenUI#2947] opened 2021-10-12 13:50 UTC
__Environment__

Onsen UI Version:

- 1.11.4

Framework:

- React with TypeScript

Framework binding:

- react-onsenui

Additional libraries:

- no

Platform:

- Windows and Android

__Encountered problem__

The toast don't work by an `onClick`

__How to reproduce__

```tsx
    <ListItem
      onClick={() => {
        if (isAndroid) {
          eruda.init();
        } else {
          ons.notification.toast("You're not on Android!", {
            timeout: 1000,
            animation: "fall",
          });
        }
      }}
      modifier="chevron"
      tappable
    >
      {string.enable_console}
    </ListItem>
```

**Comment by DerGoogler** [comment] 2021-12-04 13:19
![image](https://user-images.githubusercontent.com/54764558/144710977-90bb4a2e-17a1-455e-a49a-6a09bd39eda2.png)

**Comment by emccorson** [comment] 2022-04-06 19:20
I was not able to reproduce this locally or on the Playground.

I edited the code slightly for the Playground to the following:

```js
const App = () => 
  <Ons.ListItem
    onClick={() => {
      ons.notification.toast("You're not on Android!", {
        timeout: 1000,
        animation: "fall",
      });
    }}
    modifier="chevron"
    tappable
  >
    Click here
  </Ons.ListItem>

ons.ready(function() {
  ReactDOM.render(<App />, document.getElementById('app'));
});
```

Closing as everything seems to be working. If you are still having problems, please reply here and I will reopen the issue.

**Closed by emccorson** 2022-04-06 19:20 UTC

**Comment by emccorson** [comment] 2022-05-31 23:47
@DerGoogler Are you able to link to a GitHub repo that minimally demonstrates the problem? I wasn't able to reproduce this before with the code above.

**Comment by DerGoogler** [comment] 2022-06-01 07:22
@emccorson DerGoogler/MMRL
