### ISSUE TITLE
Event swipe use ons-gesture-detector delay 300ms Android & Iphone

### ISSUE THREAD

**Issue by pvsong** [OnsenUI/OnsenUI#1211] opened 2016-02-06 14:34 UTC
Hi, I use ons-gesture-detector to swipe left and right page but I it seem like delay 300ms or somthing else I'm not sure. But when swipe, page change for a while.
ons-gesture-detector
         id="appNavi1"
/ons-gesture-detector

ons-navigator var="app.navi" 
        ..........
/ons-navigator

$(document).on('swiperight',  '#appNavi1',  function() {
        app.navi.resetToPage("detail.html", {animation: 'slide'});
});

I've to try on Android and Iphone.

**Comment by IliaSky** [comment] 2016-02-09 03:57
Hi pvsong,
I seem to be unable to reproduce the issue. By default there should be no delay. 

Since you say that the page changes for a while, then maybe it's just that the animation takes too long - by default it's 400ms. That duration is configurable - you can set it to 150ms or 200ms so that it fits your expectations. You can try something like this:
```javascript
app.navi.resetToPage("detail.html", {animation: 'slide', animationOptions: {duration: '0.15'} });
```

If the problem still persists after tinkering with the duration settings you can also check if there is a delay with `animation: none`. If that's the case please inform us, so that we can investigate the issue.

**Comment by pvsong** [comment] 2016-02-10 07:11
Thanks for reply, but on swipe event. How can I control “speed” and/or “distance” or something like “swipe-left-end”. Because, when I swipe must to be on the entire width of device, and with speed  fast…
Thanks.

**Comment by IliaSky** [comment] 2016-02-10 07:54
Since this is already a question and not an issue I am closing this.
We can continue the discussion in [the community](https://community.onsen.io/topic/100/ons-gesture-detector/5).

**Closed by IliaSky** 2016-02-10 07:54 UTC
