### ISSUE TITLE
support ios8

### ISSUE THREAD

**Issue by ilovezy** [OnsenUI/OnsenUI#1569] opened 2016-08-31 07:35 UTC
on ios8  the dialog component did not position at center and vertical middle, suggest to add prefix to cover some css3 attributes

**Comment by argelius** [comment] 2016-09-06 03:17
@ilovezy Sorry for the late reply. We will take a look at this.

**Comment by argelius** [comment] 2016-09-12 06:45
@ilovezy I am unable to reproduce this. Can you please provide some steps to reproduce it? 

Are you running in Cordova? Can you show some very simple code that reproduces this bug?

**Comment by argelius** [comment] 2016-09-12 06:55
I will close this for now but please feel free to open it if you can provide a way to reproduce the issue.

**Closed by argelius** 2016-09-12 06:55 UTC
Labels: bug
