### ISSUE TITLE
ons-popover doesnt work for Android Devices in OnsenUI 2.0 beta

### ISSUE THREAD

**Issue by mayand** [OnsenUI/OnsenUI#1124] opened 2015-12-14 22:29 UTC
This doesn't work in Android.. (Nexus 4) and even in OnsenUI preview web page.. for some reason it works well in iPhone..

after debuging I find this error..

Uncaught (in promise) TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. {stack: (...), message: "Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'."}

.. This is coming from ons.es6 line 133.. 
document.body.appendChild(popover);

**Comment by frankdiox** [comment] 2015-12-16 01:43
@mayand It works fine in my Nexus 4 both in Chrome and webview as a Cordova app. Also I cannot see any problem in Onsen UI preview web page (you mean (this one)[http://onsen.io/2/reference/ons-popover.html#example]?). I am using Android 5.1.1. What's your version?

**Comment by frankdiox** [comment] 2015-12-24 10:36
@mayand I'm closing this since I cannot reproduce that error. Please open it again if you can provide some sort of example.

**Closed by frankdiox** 2015-12-24 10:36 UTC
Labels: bug

**Comment by mayand** [comment] 2016-01-25 04:55
My Android version is 5.1.1
