### ISSUE TITLE
OnsenUI Navigator + React failed to navigate

### ISSUE THREAD

**Issue by tonystaark** [OnsenUI/OnsenUI#2744] opened 2020-04-18 11:15 UTC
I have been banging my head against wall for days due to the issue as mentioned in the title. I was trying to implement navigation function using Onsen UI and React. However after I click to navigate, the UI navigates to a blank page, and immediately goes back to the first page. Below is my code.

     import React from "react";
     import { Page, Navigator, Button, SearchInput } from "react-onsenui";

     function EditorView() {
       return <Page>This is the editor page!</Page>;
     }

    function SearchBar() {
      return <SearchInput placeholder="Search" />;
    }
    const switchToEditorView = navigator => {
      navigator.pushPage({ component: EditorView, props: { key: "editorPage" } });
    };

    function App() {
       return (
        <Navigator
           renderPage={(route, navigator) => (
             <Page key={route.title}>
              <SearchBar />
              <Page className="custom_page_wrapper">
               <Button onClick={() => switchToEditorView(navigator)}>
                Click to navigate
               </Button>
             </Page>
            </Page>
          )}
          initialRoute={{ component: App, props: { key: "firstPage" } }}
         />
       );
     }
    export default App;

And the codesandbox is here to play with : https://codesandbox.io/s/festive-lichterman-okme5?file=/src/App.js:0-828

How to overcome it?

**Comment by kongkx** [comment] 2020-07-01 06:26
- You may need to update `renderPage` props, get the component from `route` and render it manualy.
   ```
   renderPage={(route, navigator) => { const { component: Compo } = route; return <Compo /> }}
   ```
- It seems that only deepest `Page` component is rendered.
- may import `onsenui/css/onsenui.css` for animation.

**Comment by emccorson** [comment] 2022-04-06 21:15
It looks like there is some confusion about what `renderPage` does. It is a function that takes a route object containing a component and a navigator and renders that component. In general, you will want to render the component and pass the navigator as a prop so the component can use it to push other pages.

I have edited your code slightly to make a working example:

```js
const HomeView = props =>
  <Page>
    <Button onClick={() => props.navigator.pushPage({ component: EditorView })}>
     Click to navigate
    </Button>
  </Page>;

const EditorView = () =>
  <Page>This is the editor page!</Page>;

class App extends React.Component {
  renderPage(route, navigator) {
    const props = route.props || {};
    props.navigator = navigator;

    return React.createElement(route.component, props);
  }

  render() {
    return (
      <Navigator
        renderPage={this.renderPage}
        initialRoute={{component: HomeView}}
      />
    );
  }
}
```

You should also make sure there is just one `Page` component in each view since your search bar was not rendering due to the nested pages.

Closing as not a bug/feature.

**Closed by emccorson** 2022-04-06 21:15 UTC
