### ISSUE TITLE
Safari in iOS 7, Onsen fails to init - error: TypeError: Attempting to configurable attribute of unconfigurable property.  onsenui.js:34013

### ISSUE THREAD

**Issue by CrankedCode** [OnsenUI/OnsenUI#2052] opened 2017-06-06 16:56 UTC
Using iPhone 4 (running iOS 7.1.2) and Safari.  Latest release of Onsen 2.3.2 fails to init with the following error:

Custom Elements: `Element#attachShadow` was not patched. onsenui.js:33326
TypeError: Attempting to configurable attribute of unconfigurable property.  onsenui.js:34013

Onsen is completely unusable now with the latest update on older versions of Safari.  EDIT: I have tested this on some previous versions, and the latest working that doesn't produce this error is Onsen v2.1.

**Comment by asial-matagawa** [comment] 2017-06-06 17:49
Hi, @CrankedCode!
It is caused by limitation of [a library](https://github.com/webcomponents/custom-elements/issues/70) which Onsen UI depends on and probably this problem will not be fixed in the future.
Could you consider using iOS 8+?
As we describe in [Browser Support](https://github.com/OnsenUI/OnsenUI#browser-support) section, Onsen UI is now supporting only iOS 8+.

Closing this.

**Closed by asial-matagawa** 2017-06-06 17:49 UTC
