### ISSUE TITLE
ons-input placeholder not working with angular expressions on Android

### ISSUE THREAD

**Issue by EFCniux** [OnsenUI/OnsenUI#1412] opened 2016-05-11 09:02 UTC
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 rc4
Angular 1.5.5
Cordova 6.1.1
Android (with Crosswalk), Browser (Chrome) 

__Encountered problem__
Angular expressions on an `<ons-input>` placeholder  are not being correctly displayed for modifiers "underbar" or "transparent". but work on modifier "material" or a plain html input.

On iOS 9.3.1 all seem to be working correctly.

__How to reproduce__

Html code:
```html
<div style="padding: 20px;">
    <div>
        <ons-input disable-auto-styling modifier="underbar" type="email" placeholder="{{'todo mail 1'}}"></ons-input>
    </div>
    <br>
    <div>
        <ons-input disable-auto-styling modifier="material" type="email" placeholder="{{'todo mail 2'}}"></ons-input>
    </div>
    <br>
    <div>
        <ons-input disable-auto-styling modifier="transparent" type="email" placeholder="{{'todo mail 3'}}"></ons-input>
    </div>
    <br>
    <div>
        <input type="email" placeholder="{{'todo mail 4'}}">
    </div>
</div>
```

Rendered html code:
```html
<div style="padding: 20px;">
    <div>
        <ons-input disable-auto-styling="" modifier="underbar" type="email" placeholder="todo mail 1">
            <label class="text-input__container">
                <input class="text-input text-input--underbar" placeholder="{{'todo mail 1'}}" type="email">
                <span class="_helper text-input__label text-input--underbar__label" style="color: rgba(0, 0, 0, 0.498039);">todo mail 1</span>
                <span class="input-label"></span>
            </label>
        </ons-input>
    </div>
    <br>
    <div>
        <ons-input disable-auto-styling="" modifier="material" type="email" placeholder="todo mail 2">
            <label class="text-input__container">
                <input class="text-input text-input--material" placeholder="{{'todo mail 2'}}" type="email">
                <span class="_helper text-input__label text-input--material__label" style="color: rgba(0, 0, 0, 0.498039);">todo mail 2</span>
                <span class="input-label"></span>
            </label>
        </ons-input>
    </div>
    <br>
    <div>
        <ons-input disable-auto-styling="" modifier="transparent" type="email" placeholder="todo mail 3">
            <label class="text-input__container">
                <input class="text-input text-input--transparent" placeholder="{{'todo mail 3'}}" type="email">
                <span class="_helper text-input__label text-input--transparent__label" style="color: rgba(0, 0, 0, 0.498039);">todo mail 3</span>
                <span class="input-label"></span>
            </label>
        </ons-input>
    </div>
    <br>
    <div>
        <input type="email" placeholder="todo mail 4">
    </div>
</div>
```

**Comment by frankdiox** [comment] 2016-05-11 10:46
@EFCniux Thanks for the report. Unfortunately I cannot reproduce it. It's working here: https://codepen.io/frankdiox/pen/qZvPxo?editors=101

Modifiers shouldn't affect the placeholder. Any other information?

**Comment by EFCniux** [comment] 2016-05-11 11:09
Well, I noticed that the "material" modifier was working because the placeholder being shown was the span with the class "text-input--material__label" instead of the input's placeholder, which was hidden but it's value was still `{{'todo mail 2'}}`, and all the other modifiers show the input's placeholder with an unprocessed value `{{'todo mail X'}}`. So it is probably not an issue with the modifiers themselves.

**Comment by biji** [comment] 2016-05-18 10:47
in my case, only **input type** is displayed

using Android 6

**Comment by argelius** [comment] 2016-05-26 07:32
I am also unable to reproduce this.

@EFCniux @biji Could you create a small example on Codepen that reproduces this?

Maybe you can use this tutorial as a starting point and export to Codepen:
http://tutorial.onsen.io/?framework=angular1&category=Getting%20started&module=Data%20binding

I tried changing the placeholder to an Angular string interpolation but it worked fine.

**Comment by argelius** [comment] 2016-06-13 09:11
Closing this since we are unable to reproduce. Please reopen if you are having the same problem.

**Closed by argelius** 2016-06-13 09:11 UTC
