### ISSUE TITLE
Scroll problem

### ISSUE THREAD

**Issue by byron222** [OnsenUI/OnsenUI#2577] opened 2018-11-08 02:54 UTC
when i use [ons-carousel] and [ons.notification.alert] in the same page, after close the [ons.notification.alert],
the scroll dont work....
is this a critical Onsen UI error??

**Comment by byron222** [comment] 2018-11-08 02:54
i use the 2.10.1 version

**Comment by emccorson** [comment] 2019-01-16 16:51
I'm not able to reproduce this on the latest version (2.10.6).

I used the following code (just the normal carousel playground example with a notification added):

```html
<ons-page>
  <ons-toolbar>
    <div class="left">
      <ons-toolbar-button onclick="prev()">
        <ons-icon icon="md-chevron-left"></ons-icon>
      </ons-toolbar-button>
    </div>
    <div class="center" onclick="ons.notification.alert('alert')">Carousel</div>
    <div class="right">
      <ons-toolbar-button onclick="next()">
        <ons-icon icon="md-chevron-right"></ons-icon>
      </ons-toolbar-button>
    </div>
  </ons-toolbar>

  <ons-carousel fullscreen swipeable auto-scroll overscrollable id="carousel">
    <ons-carousel-item style="background-color: #085078;">
      <div style="text-align: center; font-size: 30px; margin-top: 20px; color: #fff;">
        BLUE
      </div>
    </ons-carousel-item>
    <ons-carousel-item style="background-color: #373B44;">
      <div style="text-align: center; font-size: 30px; margin-top: 20px; color: #fff;">
        DARK
      </div>
    </ons-carousel-item>
    <ons-carousel-item style="background-color: #D38312;">
      <div style="text-align: center; font-size: 30px; margin-top: 20px; color: #fff;">
        ORANGE
      </div>
    </ons-carousel-item>
  </ons-carousel>
</ons-page>
```

```js
var prev = function() {
  var carousel = document.getElementById('carousel');
  carousel.prev();
};

var next = function() {
  var carousel = document.getElementById('carousel');
  carousel.next();
};

ons.ready(function() {
  var carousel = document.addEventListener('postchange', function(event) {
    console.log('Changed to ' + event.activeIndex)
  });
});
```

Since this is for an old version and I can't reproduce it, I'm going to close this issue. If this is still broken, please post an example that reproduces the bug and I'll reopen.

**Closed by emccorson** 2019-01-16 16:51 UTC
