### ISSUE TITLE
Issue with bad display onsen interface on IOS devices with cordova.

### ISSUE THREAD

**Issue by jonnathanlopes** [OnsenUI/OnsenUI#2718] opened 2020-01-10 03:19 UTC
I build  an application with osen and Angular and after packing on Cordova I am having bad display problem with the following devices.

IPHONE 6 bad
IPHONE 6+ bad
IPHONE 6S bad
IPHONE 6S + bad
IPHONE 7 bad
IPHONE 7+ bad
IPHONE 8 bad
IPHONE 8 + bad
IPad bad
IPad AIR 2 bad
![bad](https://user-images.githubusercontent.com/26045692/72123064-d2739300-333e-11ea-83ac-5e7c1a29bd6c.png)

In the devices below it works perfectly
![ok](https://user-images.githubusercontent.com/26045692/72123072-da333780-333e-11ea-8e8e-9b3b46848208.png)

IPHONE X OK
IPHONE XS OK
IPHONE XS MAX OK
IPHONE 11 OK

**Comment by emccorson** [comment] 2020-01-13 11:49
Can you please provide a minimum working example that replicates this issue? @jonnathanlopes

**Comment by emccorson** [comment] 2020-02-25 14:52
Aaah I just realised what the problem is. Basically you've ended up with some extra padding somewhere to account for the notch on iPhone X.

This article explains exactly what you need to do:
https://medium.com/the-web-tub/supporting-iphone-x-for-mobile-web-cordova-app-using-onsen-ui-f17a4c272fcd

I'll close this now. @jonnathanlopes

**Closed by emccorson** 2020-02-25 14:52 UTC
Labels: @WAITING FOR
