### ISSUE TITLE
Vue OnsenUi: Navigator topPage always return wrong page

### ISSUE THREAD

**Issue by ghprod** [OnsenUI/OnsenUI#1692] opened 2016-11-13 07:08 UTC
__Environment__
"onsenui": "^2.0.4",
"vue": "^1.0.21",

__Encountered problem__
When try to access `document.querySelector('#myNavigator').topPage.data`, its always return previous page, not current page

__How to reproduce__
## Some Inner Page Component Vue

```js
<script>
  export default {
    computed: {
      uuid () {
        let data = document.querySelector('#myNavigator').topPage.data

        console.log(data.uuid)

        return data.uuid
      }
    }
  }
</script>
```

**Comment by argelius** [comment] 2016-11-22 04:55
@ghprod Hi! Thanks for reporting.

I am not really sure why this is happening. This is the code for `pages` which is used by `topPage` and the code for `topPage` itself. Looking at this code I can not see how `topPage` could return anything other than the last page in the stack.

```javascript
get topPage() {
  return this.pages[this.pages.length - 1] || null;
}
```

```  
get pages() {
  return util
    .arrayFrom(this.children)
    .filter(n => n.tagName === 'ONS-PAGE');
}
```

Is it possible for you to create a simple example that reproduces this?

**Comment by ghprod** [comment] 2016-11-22 05:00
Hi @argelius 

Right now i'm using like this to get page data

```js
    ready () {
      setTimeout(() => {
        let pageData = document.querySelector('#myNavigator').topPage.data

        this.uuid = pageData.uuid
      })
    }
```

Soon i'll try to setup some codepen

**Comment by argelius** [comment] 2016-11-22 05:00
@ghprod Thank for the prompt reply!

A Codepen example would be really appreciated :+1:

**Comment by ghprod** [comment] 2016-11-22 06:01
@argelius hi, which path i should to reference latest onsen ui 2.0.4 for codepen?

Thanks

**Comment by argelius** [comment] 2016-11-22 06:09
@ghprod Please use unpkg: https://unpkg.com/onsenui@2.0.4

You can get CSS files there as well:
https://unpkg.com/onsenui@2.0.4/css/

**Comment by ghprod** [comment] 2016-11-22 06:11
Or maybe you have codepen template with vue onsen?

**Comment by munsterlander** [comment] 2016-11-22 06:30
Fork this one:  https://codepen.io/munsterlander/pen/rWWvNN

**Comment by asial-matagawa** [comment] 2017-03-21 03:26
Since `vue-onsenui@^2`, it has a completely different structure and we are no longer maintaining `vue-onsenui@^1`.

Closing this.

**Closed by asial-matagawa** 2017-03-21 03:26 UTC
Labels: vue
