### ISSUE TITLE
React | Dialog issue: dialog background invisible after first closing it

### ISSUE THREAD

**Issue by tamasfabi** [OnsenUI/OnsenUI#2585] opened 2018-11-21 10:18 UTC
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  react 15.4.2

[Framework binding]
 react-onsenui latest

[Platform]
  Desktop - OS X 10.13.6 64-bit

[Browser]
  Desktop - Chrome 70.0.3538.102 on OS X 10.13.6 64-bit
```

__Encountered problem__
  
If I cancel a simple dialog with tapping the dialog-mask and than re-open the dialog, the opacity of the mask goes back to 0, so it's invisible on further opens. It does work fine on the first open, or if the dialog is closed with the proper "close" button.

__How to reproduce__
  
1. Click the "Dialog" (first demo option).
2. Cancel it with tapping the background. (Not the close button!). 
3. Click the "Dialog" again to see the bug. 

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<div id="app"></div>
```

- __JS__

```jsx
var MyPage = React.createClass({
  getInitialState: function() {
    return {
      dialogShown: false,
      alertDialogShown: false,
      toastShown: false,
      items: [
        {
          title: 'Dialog',
          fn: this.showDialog
        },
        {
          title: 'Alert dialog',
          fn: this.showAlertDialog
        },
        {
          title: 'Toast',
          fn: this.handleShow
        },
        {
          title: 'Alert notification',
          fn: () => ons.notification.alert('An error has occurred!')
        },
        {
          title: 'Confirmation',
          fn: () => ons.notification.confirm('Are you ready?')
        },
        {
          title: 'Prompt',
          fn: () => ons.notification.prompt('What\'s your name?')
        }
      ]
    };
  },

  showDialog: function() {
    this.setState({dialogShown: true});
  },

  hideDialog: function() {
    this.setState({dialogShown: false});
  },

  showAlertDialog: function() {
    this.setState({alertDialogShown: true});
  },

  hideAlertDialog: function() {
    this.setState({alertDialogShown: false});
  },

  handleShow: function() {
    this.setState({toastShown: true});
  },

  handleDismiss: function() {
    this.setState({toastShown: false});
  },

  renderRow(row) {
    return (
      <Ons.ListItem key={row.title} tappable onClick={row.fn}>
        {row.title}
      </Ons.ListItem>
    );
  },

  renderToolbar() {
    return (
      <Ons.Toolbar>
        <div className='center'>Dialogs</div>
      </Ons.Toolbar>
    );
  },

  render: function() {
    return (
      <Ons.Page renderToolbar={this.renderToolbar}>
        <Ons.List dataSource={this.state.items} renderRow={this.renderRow} />

        <Ons.Dialog
          isOpen={this.state.dialogShown}
          isCancelable={true}
          onCancel={this.hideDialog}>
          <div style={{textAlign: 'center', margin: '20px'}}>
            <p style={{opacity: 0.5}}>This is a dialog!</p>
            <p>
              <Ons.Button onClick={this.hideDialog}>Close</Ons.Button>
            </p>
          </div>
        </Ons.Dialog>

        <Ons.AlertDialog
          isOpen={this.state.alertDialogShown}
          isCancelable={false}>
          <div className='alert-dialog-title'>Warning!</div>
          <div className='alert-dialog-content'>
            An error has occurred!
          </div>
          <div className='alert-dialog-footer'>
            <button onClick={this.hideAlertDialog} className='alert-dialog-button'>
              Cancel
            </button>
            <button onClick={this.hideAlertDialog} className='alert-dialog-button'>
              Ok
            </button>
          </div>
        </Ons.AlertDialog>

        <Ons.Toast isOpen={this.state.toastShown}>
          <div className="message">
            An error has occurred!
          </div>
          <button onClick={this.handleDismiss}>
            Dismiss
          </button>
        </Ons.Toast>
      </Ons.Page>
    );
  }
});

ons.ready(function() {
  ReactDOM.render(<MyPage />, document.getElementById('app'));
});
```

**Comment by emccorson** [comment] 2019-01-06 14:40
I can't reproduce the bug with the demo link so I'm going to close this issue.

I'm guessing this got fixed already somewhere else.

**Closed by emccorson** 2019-01-06 14:40 UTC

**Comment by tamasfabi** [comment] 2019-01-06 19:01
Indeed it must have been fixed. :)
