### ISSUE TITLE
I can't scroll inside <ons-modal> over mobile devices or chrome inspector for devices.

### ISSUE THREAD

**Issue by nikola1512** [OnsenUI/OnsenUI#2365] opened 2018-03-01 08:02 UTC
```
[Core]
    onsenui 2.7.2

[Framework]
    vue 2.5.13

[Framework binding]
    vue-onsenui 2.3.0

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

Mouse scroll is working well. When I change `ons-modal` element in DOM to `div` everything is workin perfect

https://drive.google.com/file/d/1KsiUillV1ZqEfUeFWWIum1SBVKlRPO63/view

**Comment by asialgearoid** [comment] 2018-03-22 02:18
Thanks for the video! I haven't seen this issue before. Does this still happen with the latest version of Onsen UI (2.9.2)? If so, could you reproduce it as outlined in the issue template?

@zevenzeng Could you provide a bit more information on what your issue is? If possible, please try to reproduce it as outlined in the issue template.

> 1. Go to https://tutorial.onsen.io/
> 2. Select a framework and a template
> 3. Modify the template until the issue is visible
> 4. Hit "Report an issue" button to open Github issue page. You need to be logged in on Github.
> 
> This uses the latest release of Onsen UI. In case the issue is not reproducible in desktop browsers, just follow the previous steps and also modify the platform version at the end (you can also open the mentioned site on a device).

**Comment by nikola1512** [comment] 2018-03-22 12:00
Ok, I made a new issue just like you sad. Best...

**Comment by nikola1512** [comment] 2018-03-22 12:13
Sorry, I didn't test well before I made an issue (a couple mins ago). I'll
try to reproduce once more, if not, you can close this issue because we
made a lot of changes in our code since then and who knows was this
something related to our code only.

**Comment by asialgearoid** [comment] 2018-05-01 00:10
@nikola1512 I am assuming that you have not been able to reproduce this since then, so I will close the issue. Please re-open it if this is still happening.

**Closed by asialgearoid** 2018-05-01 00:10 UTC
Labels: awaiting reply
