### ISSUE TITLE
ngx-onsenui: ng build --prod failed

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#2469] opened 2018-07-10 07:39 UTC
__Environment__

Onsen UI Version:

- 2.10.3

Framework:

- Angular 6.0.7

Framework binding:

- ngx-onsenui 4.2.2

__Encountered problem__

`cleancss-webpack-plugin` errors because of recent PR https://github.com/OnsenUI/OnsenUI/pull/2408 .

__How to reproduce__

1. Create a workspave

```
$ npm i -g @angular/cli
$ ng new my-app
$ cd my-app
$ npm i onsenui ngx-onsenui
```

2. Import `OnsenModule`  and set `CUSTOM_ELEMENTS_SCHEMA` to schemas in AppModule.

3. Add styles to `angular.json`

```
"styles": [
  "node_modules/onsenui/css/onsenui.css",
  "node_modules/onsenui/css/onsen-css-components.css",
  "src/styles.css"
],
```

4. Build the app with production mode.
```
$ ng build --prod
```

**Comment by asialgearoid** [comment] 2018-07-10 07:49
This is the second issue caused by that PR. The first caused an issue with the Theme Roller, which we fixed by changing the CSS parser. 

I think the line added in that PR should be removed, and instead the following added at [this line](https://github.com/OnsenUI/OnsenUI/blob/c075ca2b2b02647fcba1419158fe76c3ae183a84/css-components/src/components/button.css#L109):

```css
.button::-moz-focus-inner {
  outline: 0;
}
```

Could you check if that fixes the issue?

**Comment by puku0x** [comment] 2018-07-10 07:57
It fixed the problem. Thanks @asialgearoid !

**Comment by asialgearoid** [comment] 2018-07-10 07:59
Great! Feel free to create a PR and merge it right away if you have time. If not, I will do it in the morning.

**Comment by puku0x** [comment] 2018-07-10 08:02
@asialgearoid I will create a PR for this issue 👍

**Comment by puku0x** [comment] 2018-07-10 08:15
GitHub has some trouble. I can't create PR for now 😭
https://status.github.com/messages

**Closed** 2018-07-10 23:37 UTC
Labels: css
