### ISSUE TITLE
Onsen 1.3.14 android backbutton exit application instead of calling navi.popPage()

### ISSUE THREAD

**Issue by vinkvin** [OnsenUI/OnsenUI#1151] opened 2015-12-29 07:32 UTC
Hi

Im using Onsen 1.3.14. From what I've read, I thought android backbutton should be calling navi.popPage() by default, but instead my application always exited.

I also have tried using this 

![backbutton](https://cloud.githubusercontent.com/assets/11625012/12030958/e90584fa-ae38-11e5-8a7d-5d672e988254.PNG)

but it still wont work.

Is it a bug? Is there a workaround to make android backbutton not exiting the app?

Thanks.

Regards

**Comment by frankdiox** [comment] 2016-01-07 03:29
@vinkvin popPage is supposed to be the default behavior when the navigator stack is not empty so you should not need to add custom code for that. Are you loading `cordova.js`?

**Comment by vinkvin** [comment] 2016-01-08 03:24
Hi, thanks for the reply
@frankdiox Yes, I have loaded the cordova.js

**Comment by argelius** [comment] 2016-07-01 03:03
I will close this since we have been unable to reproduce the issue.

**Closed by argelius** 2016-07-01 03:03 UTC
