### ISSUE TITLE
Navigator usage with Vue JS cli project issues

### ISSUE THREAD

**Issue by sts-ryan-holton** [OnsenUI/OnsenUI#2530] opened 2018-09-04 14:30 UTC
Hi, I've recently set up a project using the Vue CLI 3.x command and I'm trying to get the Onsen UI navigator (https://onsen.io/v2/api/vue/v-ons-navigator.html) to work inside my `.vue` files.

I have a `views/Home.vue` file which comes with the project by default, and am trying to get the navigator to work with another page (e.g: `views/About.vue`).

I've tried linking to another page, the function is working and the new page is loading however there is no animation. Here's my code:

**My button that links to another page:**

```
<v-ons-back-button @click="onAboutClick();">About</v-ons-back-button>
```

**Vue JS script at the bottom of `views/Home.vue`:**

```
export default {
    name: 'home',
    methods: {
      onAboutClick: function() {
        this.$router.push({ name:'about' });
      }
    }
  }
```
This technically links to the page, but doesn't create a push/pull affect.

**Comment by sts-ryan-holton** [comment] 2018-09-18 15:03
Anyone??

**Comment by KettleCooked** [comment] 2018-09-18 15:37
Hey, I'm new to onsen, and the whole programming thing actually but I'll try to share something since it's looking a little dead in here. There's two things that come to mind:

1. First and most likely, the lack of animations is due to your use of the vue router instead of the onsen navigator. Using onsen navigator will automatically deal with animations but using the vue router you will have to manually add the animations.

2. Less likely an issue, but you are using the onsen back button. I guess adding a click event to the button it should be fine, but from what I know the back button is specific in that it will automatically search for the parent onsen navigator component and pop off the last page in the navigator stack. This is from what I understand. But you are pushing a page with the vue router, and yet popping a page with the onsen navigator. These are very different things. 

So if you want to use the vue router, do not use the ons-back-button, instead use a generic button and use a 'back button arrow" icon instead, so you don't have that extra functionality of the ons-back-back-button. But if you want the animations automatically, use the onsen navigator instead of vue router, which also means that you can easily place the ons-back-back-button anywhere with out extra work.

**Comment by KettleCooked** [comment] 2018-09-19 14:57
@sts-ryan-holton I don't blame you, I personally think Onsen has a strong product, and in some important ways was ahead of the more popular Ionic, but the community is so dead that it makes you wonder if even Monaca is still supporting Onsen.

**Comment by masahirotanaka** [comment] 2018-09-20 02:59
Sorry that it did't worked out. Since Onsen UI is based on Web Components, and requires many tweaks to support Vue and other VDOM frameworks, sometimes you feel easier to use other solutions that natively supports newer frameworks. I'm going to close this issue since this is not a bug.

@KettleCooked Yes we support Onsen but we put a bit higher priority if the user access to our official support window. Currently we are facing to deal with the trial & error for sustainable open source support.

**Closed by masahirotanaka** 2018-09-20 02:59 UTC
