### ISSUE TITLE
Tabbar is bugged when clicking tabs very quickly

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#974] opened 2015-10-21 17:06 UTC
Related: #948 (already fixed)

In this demo 
https://github.com/OnsenUI/OnsenUI/blob/master/demo/tabbar/index.html

With `fade` or `slide` animations:
- Memory leak. 
- It doesn't remove the `ons-page` from the DOM and keeps adding new pages.

With `animation: 'none'`:
- Memory leak.
- Throws: `Uncaught Error: Fail to fire "pageinit" event. Attach "ons-page" element to the document after initialization.`

**Comment by argelius** [comment] 2015-10-27 07:45
I'll take a look at this.

**Comment by argelius** [comment] 2015-11-02 03:43
@frankdiox I think this is fixed now. Can you verify?

**Closed** 2015-11-02 03:43 UTC
Labels: bug

**Comment by frankdiox** [comment] 2015-11-02 17:47
@argelius Yes, memory leak fixed :) The only thing that remains is the `pageinit` error, but since it's going to be deprecated I guess it's not very important. Thanks!

**Comment by argelius** [comment] 2015-11-04 02:29
@frankdiox Actually I was unable to reproduce the pageinit error. What browser and what version are you running?

**Comment by frankdiox** [comment] 2015-11-04 12:25
@argelius Chrome Version 46.0.2490.80 m
You have to modify the demo and use `none` for tabbar animation.
