### ISSUE TITLE
Core |  issue: <Ons.Switch checked={this.state.checked} onChange={this.handleSwitch}  > </Ons.Switch> -didnt get anyoutput for this. What I need to change to get the output.

### ISSUE THREAD

**Issue by sukaniravi** [OnsenUI/OnsenUI#2865] opened 2021-02-15 03:43 UTC
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 88.0.4324.150 on Windows 10 64-bit
```

__Encountered problem__
  

__How to reproduce__
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<Ons.Switch checked={this.state.checked} onChange={this.handleSwitch} ></Ons.Switch>

```

- __JS__

```javascript
console.log('Run your project!');
```

**Comment by emccorson** [comment] 2022-04-07 06:37
You can see the example here which uses `checked` and `onChange` props:
https://onsen.io/playground/?framework=react&category=reference&module=switch

I'll close this as not a bug/feature.

**Closed by emccorson** 2022-04-07 06:37 UTC
