### ISSUE TITLE
Vue | Tabbar issue: 

### ISSUE THREAD

**Issue by rolbr** [OnsenUI/OnsenUI#2132] opened 2017-07-29 13:39 UTC
__Environment__

  
```
[Core]
  onsenui 2.5.1
  
[Framework]
  vue 2.4.1

[Framework binding]
 vue-onsenui 2.1.0

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 59.0.3071.115 on Windows 10 64-bit
```

__Encountered problem__
When a Carousel is placed inside a Tabbar, the parameter `item-width` seems to get ignored (value not being applied to `carousel-item`) resulting in a Carousel that simply won't scroll. 

__How to reproduce__
Simply change the template entry point at `new Vue()` by un/commenting each line: `#home, #splitter, #tabbar, #splitter-tabbar`. Note `#home` and `#splitter` work as expected, the other two show the buggy behavior. Also note the width of each div (1..5 with red border) getting squished to 20% viewport width for `#tabbar` and `#splitter-tabbar` signaling the `item-width` parameter did get lost somewhere.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<template id="home">
  <v-ons-page>
    <h1>&nbsp;</h1>
    <v-ons-carousel style="display:block; width: 100%; height: 102px;" swipeable overscrollable item-width="1000px">
      <v-ons-carousel-item style="display:flex;">
        <div style="width: 200px; height: 100px; border: 1px solid red;">1</div>
        <div style="width: 200px; height: 100px; border: 1px solid red;">2</div>
        <div style="width: 200px; height: 100px; border: 1px solid red;">3</div>
        <div style="width: 200px; height: 100px; border: 1px solid red;">4</div>
        <div style="width: 200px; height: 100px; border: 1px solid red;">5</div>
      </v-ons-carousel-item>
    </v-ons-carousel>
  </v-ons-page>
</template>


<template id="splitter">
  <v-ons-page>
    
    <v-ons-splitter>
      
      <v-ons-splitter-side swipeable side="left" collapse="" width="260px" :animation="'reveal'">
        <v-ons-page>
          <div style="height: 100%; background: #CCC;">
            Menu
          </div>
        </v-ons-page>
      </v-ons-splitter-side>
      
      <v-ons-splitter-content>
        <v-ons-page>
          <h1>Splitter > Home <span style="font-size: 0.7rem; font-weight: normal; display: block;">(Menu on the left)</span></h1>
          
          <!-- this is the EXACT SAME carousel markup as in 'Home'-->
          <v-ons-carousel style="display:block; width: 100%; height: 102px;" swipeable overscrollable item-width="1000px">
            <v-ons-carousel-item style="display:flex;">
              <div style="width: 200px; height: 100px; border: 1px solid red;">1</div>
              <div style="width: 200px; height: 100px; border: 1px solid red;">2</div>
              <div style="width: 200px; height: 100px; border: 1px solid red;">3</div>
              <div style="width: 200px; height: 100px; border: 1px solid red;">4</div>
              <div style="width: 200px; height: 100px; border: 1px solid red;">5</div>
            </v-ons-carousel-item>
          </v-ons-carousel>
        </v-ons-page>
      </v-ons-splitter-content>
      
    </v-ons-splitter>
  </v-ons-page>
</template>



<template id="tabbar">
  <v-ons-page>
    <h1>Tabbar > Home</h1>
    
    <evil-tabbar></evil-tabbar>
    
  </v-ons-page>
</template>



<template id="splitter-tabbar">
  <v-ons-page>
    
    <v-ons-splitter>
      
      <v-ons-splitter-side swipeable side="left" collapse="" width="260px" :animation="'reveal'">
        <v-ons-page>
          <div style="height: 100%; background: #444;">
            Menu
          </div>
        </v-ons-page>
      </v-ons-splitter-side>
      
      <v-ons-splitter-content>
        <v-ons-page>
          <h1>Splitter > Tabbar ></h1>
          <div>
            
            <evil-tabbar></evil-tabbar>
            
          </div>
        </v-ons-page>
      </v-ons-splitter-content>
      
    </v-ons-splitter>
  </v-ons-page>
</template>



<template id="settings">
  <v-ons-page>
    <p style="text-align: center">
      Change the settings.
    </p>
  </v-ons-page>
</template>


<div id="app"></div>
```

- __JS__

```javascript

Vue.component('evil-tabbar', {
  template: `
  <v-ons-tabbar position="auto">
    <ons-tab icon="ion-home" page="home" active></ons-tab>
    <ons-tab icon="ion-ios-settings" page="settings"></ons-tab>
  </v-ons-tabbar>
  `
});

const homePage = {
  template: '#home'
};

const settingsPage = {
  template: '#settings'
};

new Vue({
  el: '#app',
  template: '#home' // OK
  // template: '#splitter' // OK
  // template: '#tabbar' // Carousel-Item is 100% width instead of 1000px
  // template: '#splitter-tabbar' // // Carousel-Item is 100% width instead of 1000px
});
```

**Comment by frandiox** [comment] 2017-07-29 13:59
@rolbr Thanks for making this demo! I've found an issue in the code. Your `evil-tabbar` is truly evil because it includes `ons-tab` custom elemnet instead of `v-ons-tab` Vue component :P
Due to this, `page` attribute is loading `<ons-page>` custom element rather than `<v-ons-page>` Vue component. A quick fix is as follows:

```
Vue.component('evil-tabbar', {
  template: `
  <v-ons-tabbar position="auto">
    <template slot="pages">
      <home-page></home-page>
      <settings-page></settings-page>
    </template>
    <v-ons-tab icon="ion-home" active></v-ons-tab>
    <v-ons-tab icon="ion-ios-settings"></v-ons-tab>
  </v-ons-tabbar>
  `,
  components: {homePage, settingsPage}
});
```

[Codepen here](https://codepen.io/frankdiox/pen/eEJZRb?editors=1010). There is also another syntax for `v-ons-tabbar` using `:tabs` prop instead of `slot="pages"`, see [this tut](http://tutorial.onsen.io/?framework=vue&category=reference&module=tabbar).

Once it is fixed, I cannot see the Carousel issue anymore. If you remove `overscrollable` attribute and are at index 0, the drag event will be used by the Splitter since the Carousel cannot consume it.

**Comment by rolbr** [comment] 2017-07-29 14:14
Whoa, thanks @frandiox for getting back to this so quickly. I could have sworn I had double-checked the elements for mising `v-` at least three times. Blimey! The Codepen works just fine indeed.

However, in my local project I _am_ in fact using the :tabs=[...] way of providing the pages, so there's presumably no issue with `ons-tab` instead of `v-ons-tab` being used. Guess I have to spend a little more time looking into this.

And I actually like the way the Carousel keeps the touchmove for itself and doesn't bubble up to the Splitter. I think the Splitter should only react when dragging on non-interactive elements, like plain text etc.

Again, thanks for the quick fix! I'll have another look at my local code. Maybe I'll test with `slot="pages"` **instead** of `:tabs=[...]` and see what happens.

**Comment by frandiox** [comment] 2017-07-30 23:27
@rolbr I just tried that Codepen with `:tabs` prop and still works well, so I guess we can close this issue for now. Feel free to open it again (or a new one) if you can reproduce what happens in your local environment :+1:

**Closed by frandiox** 2017-07-30 23:27 UTC

**Comment by rolbr** [comment] 2017-07-31 07:49
Looks like restarting the dev server wasn't enough — but after rebooting the machine everything's fine. So essentially all I did was updating the NPM modules to

    "onsenui": "^2.5.1",
    "vue": "^2.4.2",
    "vue-onsenui": "^2.1.0",

and somewhere on the way it got fixed. As of now, I cannot reproduce the issue anymore. Thanks!
