### ISSUE TITLE
Unhandled Toast Error: Cannot read property 'visible' of null

### ISSUE THREAD

**Issue by chris-guidry** [OnsenUI/OnsenUI#2538] opened 2018-09-17 20:45 UTC
__Environment__

Onsen UI Version:
2.9.1

Framework:
React 16.3.2

Framework binding:
react-onsenui 1.10.0

Additional libraries:
react-router 3.2.0

Platform:
All

__Encountered problem__
Unhandled error in Toast: TypeError: Cannot read property 'visible' of null.

In debugging the error, it looks like it's in BaseDialog.jsx line 75:
```
if (**this.node.firstChild.visible** === true) {
    this.node.firstChild.hide().then(unmount);
} else {
    unmount();
}
```

__How to reproduce__
I have only encountered this error in one scenario:
1. Display toast message.
2. Route to a new component.
3. Route back to previous component.

It seems there is not a "firstChild" when the component loads. Maybe line 44, `this.node = document.createElement('div');`, could be changed to include a child? 

I tried upgrading to the latest versions for both onsenui (2.10.4) and react-onsenui (1.11.1), but the issue persisted. I ended up going back to the versions listed above because of a few changes I wasn't ready to deal with.

**Comment by petercutting** [comment] 2018-11-11 12:33
I ran in to same scenario. It turned out that upgrading react and react-dom from 15.6.? to 16.? was the culprit. Had to checkout and test lots of my app's old git versions to home in on it

**Comment by chris-guidry** [comment] 2018-12-03 01:59
@petercutting thanks for the input. I added error handling via componentDidCatch for now. I am not going to downgrade React, but I am hoping Onsen will get updated to resolve the issue.

**Comment by fabiosussetto** [comment] 2019-02-06 09:17
I can confirm this is a problem with React 16.x and the latest version of OnsenUI

**Comment by emccorson** [comment] 2022-04-06 22:31
I _think_ this should be fixed in the linked PR since the offending code has been removed. However, I wasn't able to test it since there is no example included in this issue. I have marked it as fixed by the PR, but if it turns out to still be a problem I will reopen this issue.

**Closed** 2022-04-07 20:00 UTC
Labels: @REPRODUCE
