### ISSUE TITLE
Tabbar not displayed correctly in Splitter Side Component

### ISSUE THREAD

**Issue by ThomasLochbrunner** [OnsenUI/OnsenUI#1600] opened 2016-09-22 08:00 UTC
**Environment**
Onsen 2.0
Angular 1.5.2
iOS 9.3.5
Firefox 48+

**Encountered problem**
The tabbar seems not to be displayed correctly when used in the splitter side component. I first encountered this issue when on iOS and in Firefox all Icons of my tabbar "changed" to the cloud-icon after updating from onsen 2rc17 to version 2.0. In chrome everything is still working fine (besides the fact that the splitter side component there is overlapping the splitter content, but until now I´m not able to reproduce this problem...). 
While trying to reproduce the problem I have come to a point where the whole tabbar is not displayed in Firefox and iOS, but is displayed in chrome. See codepen below to test/reproduce this issue.

**How to reproduce**
https://codepen.io/anon/pen/vXgygk

**Comment by misterjunio** [comment] 2017-04-05 04:19
@ThomasLochbrunner I couldn't reproduce your errors so I assume it got solved meanwhile. Anyway the point of Onsen is to emulate native apps so I would say that having a `tabbar` inside the `splitter-side` is a poor design idea from the start and not an intended component use to begin with so I will close this issue

**Closed by misterjunio** 2017-04-05 04:19 UTC
Labels: angular1
