### ISSUE TITLE
Some testcases fail on Cordova + iOS 10.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1586] opened 2016-09-15 09:05 UTC
@argelius  I tested `examples/*/index.html` on `rc.18` + Cordova + iOS 10 and some testcases fail.

## Environment

 * Onsen UI 2.0.0-rc.18
 * iOS 10
 * Cordova 6.3.1

## Encountered problem

 * ons-page and ons-toolbar: status bar padding is nothing.
![image](https://cloud.githubusercontent.com/assets/59784/18544109/2b745502-7b6e-11e6-92d3-9f742f271324.png)

 * ons-navigator(examples/navigator/index.html): `undefined` title is shown on second page.
![image](https://cloud.githubusercontent.com/assets/59784/18544134/4acc4f72-7b6e-11e6-88e6-9f31e805e295.png)

 * ons-list(examples/list/index.html): ons-list has device 2px border. It should be device 1px.
![image](https://cloud.githubusercontent.com/assets/59784/18544203/874275e4-7b6e-11e6-96c8-18b39f8d31f1.png)

**Comment by argelius** [comment] 2016-09-15 09:10
@anatoo Thank you for testing!

The status bar filling needs to be fixed before releasing, I was not aware of it failing

**Comment by argelius** [comment] 2016-09-15 09:25
By the way, I don't think the `undefined` in the first example is not a bug. I think it's just how the example is written.

**Comment by anatoo** [comment] 2016-09-15 09:30
That's right. However user developers may think Onsen UI is just broken when see `ons-navigator` example. Also it should be fixed.

**Comment by argelius** [comment] 2016-09-15 09:30
@anatoo That's true, let's fix the example

**Comment by anatoo** [comment] 2016-09-15 09:49
@argelius I had a mistake. Examples does not loaded `cordova.js` and the status bar filling is fixed after adding script tag to load `corodva.js`. 
Next I will fix `ons-navigator` example issue.

**Comment by anatoo** [comment] 2016-09-15 09:57
I just fixed `ons-navigator` example issue on this commit: https://github.com/OnsenUI/OnsenUI/commit/b2ff3c71298e7392c691554d670079e05b5a3158

**Comment by argelius** [comment] 2016-09-15 09:58
Thanks @anatoo!

**Comment by argelius** [comment] 2016-09-16 04:12
Will close this for now. I will take a look at the list border today

**Closed by argelius** 2016-09-16 04:12 UTC
