### ISSUE TITLE
Sliding Menu and Navigator Combinations

### ISSUE THREAD

**Issue by murliatdure** [OnsenUI/OnsenUI#811] opened 2015-07-26 06:58 UTC
Hello,
facing issues with the Sliding Menu and Navigator combination for routing.
- Only Sliding works well
- Only Navigator works well
- Combining both, no issue only 1 scenario tends to FATAL
- If i navigate via Sliding Menu (works well - no issues) and navigate after that appNavi.Push(..) is failing

![image](https://cloud.githubusercontent.com/assets/7137859/8892888/daee0b34-3391-11e5-9cf4-7caafdae0825.png)

Please assist for the same.

**Comment by murliatdure** [comment] 2015-07-26 06:59
After this issue, whole application navigator navigation fails.

**Comment by argelius** [comment] 2015-07-27 02:10
Hi @murliatdure !

Can you please create an example that reproduces this? It looks like the navigator element is destroyed.

**Comment by murliatdure** [comment] 2015-07-27 06:26
Can you please share the support email ID where I can share the HTML Skeleton and usage.
Would be great if I share the deck as is.

**Comment by murliatdure** [comment] 2015-07-27 17:08
Hello,
Sharing the deck for reproducing the issue.
Steps to reproduce:1. Login - <navigator works>2. HomePage : Navigate between M1, M2 - <navigator works>3. Try to navigate between the Sliding Menu Items .. Settings, Home, etc. <menu is ok>4. Logout <menu redirects to the Login page again>5. Now try to Login again <FAILS>

Observations:Once Menu navigation used, the Navigator Fails afterwards; till whole page refreshes.
Also, with the same deck unable to override the BACK BUTTON on android.
Please assist me on this.
Thanks,

**Comment by murliatdure** [comment] 2015-07-31 14:49
Any updates.. as this is a blocker.

**Comment by mork80** [comment] 2015-08-08 08:48
I did as follow
create a "fake page" with navigator
   <ons-template id="loading.html">
   <ons-navigator var="myNav">
    <ons-page id="loading">
      <div>Loading..........</div>
    </ons-page>
    </ons-template>

Then at the bottom of html file (i use single html with multipage)
<ons-template id="menu.html">   
      <ons-page modifier="menu-page">
        <ons-toolbar modifier="transparent">
          <div class="center">
            uFirst Logo
          </div>
        </ons-toolbar>
        <ons-list class="menu-list">
          <ons-list-item class="menu-item" onclick="menuClick('list1.html');">
            <ons-icon icon="ion-map"></ons-icon>
            List 1
          </ons-list-item>
         <ons-list-item class="menu-item" onclick="menuClick('list2.html')">
            <ons-icon icon="ion-ios-list-outline"></ons-icon>
            List 2
          </ons-list-item>
        </ons-list>
    </ons-page>
</ons-template>
----------------------
JS functions
----------------------

var pushMenuPage='';
 function menuClick(targetPage){
          pushMenuPage=targetPage;
          menu.setMainPage('loading.html', {closeMenu: true})
      }

document.addEventListener("pageinit", function(e) {
if (e.target.id == "loading") {
          console.log("trying to push from menu click");
          myNav.pushPage(pushMenuPage, { animation: "lift" });
        }
}


Use in link/buttons push and pop functions as usual with the myNav navigator.
Hope this helps, It worked for me

NF

**Comment by msaelices** [comment] 2017-11-24 02:59
I also have problems with navigation and splitters. Look at this app:

https://msaelices.github.io/react-onsenui-redux-weather/demo.html

The home page code is there:

https://github.com/msaelices/react-onsenui-redux-weather/blob/912df7535eaefdd861067c55339787ee27396516/src/components/MainPage.js

The issue is that, if you click in some item in the list, the app does a [pushPage](https://github.com/msaelices/react-onsenui-redux-weather/blob/912df7535eaefdd861067c55339787ee27396516/src/containers/Location.js#L74), but the [backbutton](https://github.com/msaelices/react-onsenui-redux-weather/blob/912df7535eaefdd861067c55339787ee27396516/src/components/NavBar.js#L28) does not appears.

**Comment by asialgearoid** [comment] 2018-05-01 00:40
This issue is for Onsen UI v1, so I will close it. @msaelices If you are still having problems, please open a new issue, as it makes it much easier to follow -- I didn't see your comment on this until just now, but I would see a new issue right away.

**Closed by asialgearoid** 2018-05-01 00:40 UTC
