### ISSUE TITLE
Vue | Switch issue: checked prop doesn't work

### ISSUE THREAD

**Issue by pzanitti** [OnsenUI/OnsenUI#2529] opened 2018-08-29 00:25 UTC
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  vue 2.4.1

[Framework binding]
 vue-onsenui latest

[Platform]
  Desktop - OS X 10.13.6 64-bit

[Browser]
  Desktop - Chrome 68.0.3440.106 on OS X 10.13.6 64-bit
```

__Encountered problem__
  
Switch docs say:
>To make the switch enabled by default you can use the checked prop just like with radio buttons and checkboxes.

But radio and checkbox docs don't mention anything about it.

__How to reproduce__
  
Pass a true value to `:checked`, it will still be unchecked. `:disabled` works fine.

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">Form input</div>
    </v-ons-toolbar>

    <ons-list>
      <ons-list-item>
        <label class="center" for="switch1">
          Switch ({{ switchOn ? 'on' : 'off' }})
        </label>
        <div class="right">
          <v-ons-switch input-id="switch1"
            :checked="switchOn"
          >
          </v-ons-switch>
        </div>
      </ons-list-item>
      
      <ons-list-item>
        <label class="center" for="switch2">
          Switch ({{ switchOn ? 'on' : 'off' }})
        </label>
        <div class="right">
          <v-ons-switch input-id="switch2"
            :disabled="switchOn"
          >
          </v-ons-switch>
        </div>
      </ons-list-item>
    </ons-list>
  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      switchOn: true
    };
  }
});
```

**Comment by wotsushi** [comment] 2018-09-30 13:08
I reproduced this issue and I found a problem by using a debugger.

Whether or not `:chekced` of `v-ons-switch` is passed, the property `$el.checked` of [modelCheckbox](https://github.com/OnsenUI/OnsenUI/blob/master/bindings/vue/src/mixins/model.js#L47) (Note: `v-ons-switch` includes `modelCheckbox`) is assigned to the following exception:

```
TypeError: Cannot read property 'checked' of null
    at HTMLElement.get$$1 (onsenui/js/onsenui.js:19515:26)
    at HTMLElement.remoteFunction (<anonymous>:2:14)
    at VueComponent._updateValue (vue-onsenui/dist/vue-onsenui.js:409:7)
    at VueComponent.mounted (vue-onsenui/dist/vue-onsenui.js:390:10)
    at callHook (vue/dist/vue.js:2921:21)
    at Object.insert (vue/dist/vue.js:4152:7)
    at invokeInsertHook (vue/dist/vue.js:5947:28)
    at Vue.patch [as __patch__] (vue/dist/vue.js:6166:5)
    at Vue._update (vue/dist/vue.js:2660:19)
    at Vue.updateComponent (vue/dist/vue.js:2788:10)
```

On the other hand, the property `$el.disabled` of `modelCheckbox` is assigned to `true` or `false`, not an exception.

**Comment by StaymanHou** [comment] 2020-01-03 21:46
+1 on this issue. Just ran into it.

I was able to find a temporary workaround. Just replace `:checked` with `:modelProp`. It doesn't look so clean though.

**Comment by emccorson** [comment] 2021-06-16 07:05
I've just come back to this issue as part of the upgrade to support Vue 3.

This is actually a documentation problem. `checked` shouldn't be a prop support by VOnsSwitch because the behaviour is already covered by using `v-model`. The only difference between `checked` and `v-model` is that `checked` is a one-way binding and `v-model` is two-way. I expect for most cases we would want two-way binding (to register user interaction with the switch), so  the solution is to remove `checked` from the VOnsSwitch documentation.

To set the VOnsSwitch as checked, use `v-model`:

```vue
<template>
  <v-ons-switch v-model="checked"></v-ons-switch>
</template>

<script>
export default {
  data() {
    return {
      checked: true
    }
  }
}
</script>
```

If you absolutely need one-way data binding, you can set `v-bind` instead (same suggestion as @StaymanHou):

```html
// vue-onsenui for Vue 2
<v-ons-switch :modelProp="true"></v-ons-switch>

// vue-onsenui for Vue 3 (yet to be released)
<v-ons-switch :modelValue="true"></v-ons-switch>
```

I have created two issues to track the needed documentation changes:
#2901
#2861

**Closed by emccorson** 2021-06-16 07:05 UTC
