### ISSUE TITLE
ons-switch not working on iOS and Safari

### ISSUE THREAD

**Issue by vjoomens** [OnsenUI/OnsenUI#1657] opened 2016-10-27 09:31 UTC
**Environment**
Onsen 2.0.3
Angular 1.5.8
iOS, Safari (sierra)

**Encountered problem**
The ons-switch element is not working on Safari or iOS.

**How to reproduce**
https://codepen.io/vjoomens/details/JRVbZR/

**Comment by argelius** [comment] 2016-11-01 03:44
@vjoomens Thanks for reporting!

@asial-matagawa Can you please investigate this issue?

**Comment by asial-matagawa** [comment] 2016-11-02 08:02
@argelius
Now I am preparing a better testing environment for iOS WebView / macOS Safari.
After that, I will investigate this issue. Thank you.

**Comment by asial-matagawa** [comment] 2016-12-09 18:35
@vjoomens 
I have investigated this issue.

Result of the investigation:
- This issue is caused by both of `ons-sliding-menu` element defined in `angular-onsenui` and `ng-model` attribute.
    - `ons-sliding-menu` element is there for backward compatibility reasons.
    - The new component for the menu is [`ons-splitter`](https://onsen.io/v2/docs/angular1/ons-splitter.html) element.
    - If you use `ons-splitter` instead of `ons-sliding-menu`, it will work fine.

Here is a minimum example to reproduce this problem:
```html
<ons-sliding-menu>
  <div class="main">
    <ons-page>
      <!-- If we remove the ng-model attribute, it works fine. -->
      <ons-switch ng-model="test"></ons-switch>
    </ons-page>
  </div>
</ons-sliding-menu>

<!-- If we use ons-splitter, it works fine. -->
<!--
<ons-splitter>
  <ons-splitter-content>
    <ons-page>
      <ons-switch ng-model="test"></ons-switch>
    </ons-page>
  </ons-splitter-content>
</ons-splitter>
-->
```

```js
angular.element(document).ready(function () {
    angular.bootstrap(document, ['onsen']);
});
```

A CodePen for this issue is also available:
https://codepen.io/anon/pen/ENpNXK?editors=1010#0

**Comment by Chozzle** [comment] 2017-03-20 15:39
This is still a problem for me on iOS 9.3.5 with Cordova.

**Comment by Chozzle** [comment] 2017-03-20 16:01
The problem remains for me on iOS 9.3.5. I'm using ons-splitter and the problem persists. Removing ng-model does fix it.

**Comment by misterjunio** [comment] 2017-04-07 09:21
@vjoomens we are about to remove `ons-sliding menu` so like @asial-matagawa recommended I would switch (pun intended) to `ons-splitter`, I think the problem should be gone.

@Chozzle can you provide an example where it does not work for you? It is working for me..

Small example: https://codepen.io/misterjunio/pen/vxqBvZ?editors=1011

**Comment by misterjunio** [comment] 2017-05-25 03:15
I believe the problem is solved in recent versions, closing this.

**Closed by misterjunio** 2017-05-25 03:15 UTC
Labels: angular1, bug, ios
