### ISSUE TITLE
Angular2 | List issue: ons-select inside ons-list-item kill browser tab with endless errors in console

### ISSUE THREAD

**Issue by georgeMuraveiAlkh** [OnsenUI/OnsenUI#2574] opened 2018-10-24 17:44 UTC
__Environment__

  
```
[Core]
  onsenui 2.10.5
  
[Framework]
  angular2 7.0.0

[Framework binding]
 angular2-onsenui latest

[Platform]
  Desktop - OS X 10.14.0 64-bit

[Browser]
  Desktop - Chrome 70.0.3538.67 on OS X 10.14.0 64-bit
```

__Encountered problem__
ons-select inside ons-list-item with *ngFor directive placed on <option> kill browser tab with endless errors in console
```
ERROR TypeError: Cannot read property 'remove' of null
    at HTMLElement.remove (VM109 onsenui.js:27066)
    at VM109 onsenui.js:18696
    at Array.forEach (<anonymous>)
    at HTMLElement._compile (VM109 onsenui.js:18684)
    at VM109 onsenui.js:18652
    at VM109 onsenui.js:5557
    at Array.forEach (<anonymous>)
    at consumeQueue (VM109 onsenui.js:5556)
    at contentReady (VM109 onsenui.js:5572)
    at HTMLElement.connectedCallback (VM109 onsenui.js:18860)
```

__How to reproduce__
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<app></app>
```

- __JS__

```typescript
import {
  Component,
  OnsenModule,
  NgModule,
  CUSTOM_ELEMENTS_SCHEMA
} from 'ngx-onsenui';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

@Component({
  selector: 'app',
  template: `
  <ons-page>
  <ons-toolbar>
    <div class="center">Lists</div>
  </ons-toolbar>

  <ons-list>
    <ons-list-header>Default</ons-list-header>
    <ons-list-item>
      <ons-select>
        <option *ngFor="let i of list" [value]="i">{{i}}</option>
      </ons-select>
    </ons-list-item>
    <ons-list-item>Item B</ons-list-item>
  </ons-list>
</ons-page>
  `
})
export class AppComponent {
}

@NgModule({
  imports: [OnsenModule],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
class AppModule { 
  list = ['One', 'Two']
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by puku0x** [comment] 2018-10-25 04:16
@georgeMuraveiAlkh I found the variable `list` was not defined in `AppComponent`.
I think that was why the code did not work for you.

```ts
import {
  Component,
  OnsenModule,
  NgModule,
  CUSTOM_ELEMENTS_SCHEMA
} from 'ngx-onsenui';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

@Component({
  selector: 'app',
  template: `
  <ons-page>
    <ons-toolbar>
      <div class="center">Lists</div>
    </ons-toolbar>
    <div class="content">
      <ons-list>
        <ons-list-header>Default</ons-list-header>
        <ons-list-item>
          <div class="center">
            <ons-select>
          　   <option *ngFor="let i of list" [value]="i">{{i}}</option>
            </ons-select>
          </div>
        </ons-list-item>
        <ons-list-item>Item B</ons-list-item>
      </ons-list>
    </div>
  </ons-page>
  `
})
export class AppComponent {
  list = ['One', 'Two'];  // Here!
}

@NgModule({
  imports: [OnsenModule],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
```

Cheers!

**Comment by georgeMuraveiAlkh** [comment] 2018-10-25 15:18
@puku0x yes, my bad, but I missed it only in example, also getting errors in "playground" with loading dependencies(404 errors). Anyway in editor I'm getting 1 error while initialization and locally I'm getting endless errors: 
```
ERROR TypeError: Cannot read property 'remove' of null
    at HTMLElement.remove (VM109 onsenui.js:27066)
    at VM109 onsenui.js:18696
    at Array.forEach (<anonymous>)
    at HTMLElement._compile (VM109 onsenui.js:18684)
    at VM109 onsenui.js:18652
    at VM109 onsenui.js:5557
    at Array.forEach (<anonymous>)
    at consumeQueue (VM109 onsenui.js:5556)
    at contentReady (VM109 onsenui.js:5572)
    at HTMLElement.connectedCallback (VM109 onsenui.js:18860)
```

**Comment by emccorson** [comment] 2019-01-06 15:14
I think this is just errors in user code, not a bug with Onsen UI, so I'm going to tentatively close this. If it is actually a bug please correct me.

**Closed by emccorson** 2019-01-06 15:14 UTC
