### ISSUE TITLE
We should remove all DOM structure mutation on `createdCallback()` and `attachedCallback()`.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1262] opened 2016-02-25 10:05 UTC
Currently several core elements (e.g ons-page, ons-navigator, ons-switch) mutate DOM structure on the initialization.

`ons-page` Example:

HTML:

``` html
<ons-page>
  <ons-toolbar>
     <div class="center">Title</div>
  </ons-toolbar>

  <div>foobar</div>
</ons-page>
```

DOM after initialization:

``` html
<ons-page class="page">
  <ons-toolbar>
     <div class="center">Title</div>
  </ons-toolbar>
  <div class="page__content">
    <div>foobar</div>
  </div>
  <div class="page__background"></div>
</ons-page>
```

This behavior  break Angular2 DOMRenderer and Virtual DOM based frameworks like React.

We should remove all DOM structure mutation(not style and attribute) on `createdCallback()` and `attachedCallback()`. For example, `ons-page` should be like the below to remove DOM structure mutation on initialization.

HTML:

``` html
<ons-page>
  <ons-toolbar>
    <div class="center">Title</div>
  </ons-toolbar>
  <ons-page-content>
    foobar
  </ons-page-content>
  <ons-page-background></ons-page-background>
</ons-page>
```

Alternately, I think we can wait Shadow DOM implementation on mobile browsers and use Shadow DOM instead of removal DOM structure mutation on initialization.

@OnsenUI/owners  @OnsenUI/members How do you think about this problem?

**Comment by argelius** [comment] 2016-02-25 11:07
Thanks @anatoo !

Also @philolo1 is having some major issues making bindings for React.

I think we should let the frameworks do all the DOM manipulation. I will try to write some React code today and tomorrow and see if I can figure how we can wrap the `<ons-navigator>` in a better way and what changes needs to be made.

Basically for things like managing the page stack och the navigator the frameworks must handle removing and adding the DOM elements but I think we should still leverage the core library for the animations.

**Comment by philolo1** [comment] 2016-02-25 11:42
@argelius I had issues with the navigator but the way it works now pretty well, the only thing is that its rendering twice, but with the benefit of using the actual functions. Please have a look at OnsNavigator in my code before you try to rewrite it yourself :) and take a look at the examples. Its definetly not an easy task :)

**Comment by anatoo** [comment] 2016-02-25 11:43
@argelius I think we should remove DOM tree mutation on *only* initialization. It's OK that have ons-navigator's pushPage or other methods that mutate DOM.

**Comment by philolo1** [comment] 2016-02-25 11:52
@anatoo i don't know how it looks in angular, but in react i set the  _compile='true' property and just create the dom as it would be done in the compile function. For example in onspage i do something like this

```<ons-page   {...this.props}  _compiled="true" >
        {toolbar}
        <div className="page__background"> </div>
        <div className="page__content">
          {otherChildren}
        </div>
        <div className="page__extra" style={{zIndex: 10001}}>
          {modal}
        </div>
      </ons-page>;```

**Comment by argelius** [comment] 2016-02-25 12:03
@anatoo: Oh, I thought there was also a problem when the components make manipulations after init.

As @philolo1 is saying, this is already possible by adding `_compiled` attributed.

**Comment by anatoo** [comment] 2016-02-25 12:54
@philolo1 @argelius Oh it's good! But the all attributes is not available when an element is created by document.createElement() and Angular2 use document.createElement().

**Comment by anatoo** [comment] 2016-02-25 13:03
あと名前がちょっと良くない気がします。
'_compiled' is not good name in this use case.

**Comment by frankdiox** [comment] 2016-02-25 13:18
@anatoo Perhaps every element could "export" its final DOM scheme or "templateSource" without actually compiling. I mean, something like what `ons-dialog` has:
```
const templateSource = util.createElement(`
  <div>
    <div class="dialog-mask"></div>
    <div class="dialog">
      <div class="dialog-container"></div>
    </div>
  </div>
`);
```

Bindings can get that and compile it in their own way. This way we don't need to maintain schemes in all the bindings, only in the core.
In case there is no bindings then it will be compiled normally by the core. As @argelius was saying this evening, we can have some toggle for that or just rewrite some "compile" method from the bindings.

**Comment by anatoo** [comment] 2016-02-25 13:36
@frankdiox '_compiled' attribute is not available on using createElement(). And what was worse, Angular2 set all attributes after an element is attached.
Related: https://github.com/OnsenUI/OnsenUI/issues/1261

**Comment by sukima** [comment] 2017-01-03 04:21
> And what was worse, Angular2 set all attributes after an element is attached.

Just spent a week vacation writing an [Ember.js addon](https://github.com/sukima/ember-onsenui) addon and ran into this very issue with `<ons-input>`.

The problem I ran into was that some attributes (`content-left` and `type`) are attributes that change how the `init()`/`_compile()` methods behave. This is all well and good in HTML where the syntax is `<ons-input type="text" content-leff></ons-input>` but completely defeated in cases when the element is created dynamically.

```js
var inputEl = document.createElement('ons-input');
inputEl.setAttribute('content-left', true); // Ignored; _compile already executed.
inputEl.setAttribute('type', 'text'); // Fails! type is defined as a getter only no setter
// If there was a setter it would not matter as it would also be ignored because
// _compile already executed.
```

As far I can tell the above is the correct way to manage web-components in JavaScript. The DOM API does not have a way to initialize web-components but to only mutate their attributes after the fact.

I suggest the initialization logic (building child DOM nodes and appending them) be moved from the `constructor` to the `connectedCallback` as described:

> Called every time the element is inserted into the DOM. Useful for running setup code, such as fetching resources or rendering. **Generally, you should try to delay work until this time.**

(emphasis mine)

Unless I'm missing something stupid… 🙏

**Comment by frankdiox** [comment] 2017-01-03 09:23
@sukima Thanks for spending some time with this! I don't have too much time now but perhaps [this could be helpful](https://codepen.io/frankdiox/pen/oBNxXK?editors=0010).

We made `ons-input` before having bindings so I agree on the API not being the best for this purpose. 

Anyway, if I'm not wrong the `_compile` function it's run after being attached to the DOM because of `contentReady` function. `contentReady` was implemented for compatibility with the bindings and it basically delays the compilation until the element gets some content (`ons-input` doesn't have content) or the function is called again. In this case, it is called again from `connectedCallback` so basically it's compiled after that. Just try to set `type` attribute before anything else since other attributes may force `contentReady` as well (like 'modifier' or 'placeholder').

You can ignore the `content-left` attribute since it's not very useful and probably will be removed.

Hope this helps! I will close this issue since it's quite old and the core was already modified to make the DOM mutation "optional". Please open a new issue for any other question :)

**Closed by frankdiox** 2017-01-03 09:23 UTC
Labels: core

**Comment by sukima** [comment] 2017-01-03 11:51
@frankdiox Thanks. Got it working. The trick was to make sure I set the `type` attribute *after* it was created and **before** it got rendered. Thanks to Ember providing good component life hooks I was able to pull this off (`willInsertElement` vs. `didInsertElement`). Phew!

**Comment by sukima** [comment] 2017-01-03 14:28
@frankdiox Sorry I just dived into this further. **This is not working** Why? `setImediate` delays the constructor for one call execution which means it happens prior to `setAttribute`. Sorry but most people working with web components will have a difficult time inserting a hook between the constructor and the `setImediate`. (https://github.com/OnsenUI/OnsenUI/blob/master/core/src/ons/content-ready.js#L59-L62)

The `contentReady` makes assumptions that just are not there in frameworks. In fact I believe it is depended on how browsers implement HTML parsing and not how the DOM API was intended to be used.

Moving the DOM manipulation logic to `connectedCallback` I think will fix the issue. An alternative would be to avoid the `setImediate` and instead have the `connectedCallback` functions flush the `contentReady` queue. Then we know the content is really ready.

**Comment by lzrski** [comment] 2017-11-23 15:40
Hello. Thanks for your work on OnsenUI. It's very impressive.

I was trying to use it together with Elm, which is a purely functional language with a virtual DOM framework. Unfortunately I've run into the issue discussed above. Because `ons-page` is manipulating the DOM tree, applying diffs to the DOM is failing. After a model is updated, patching the DOM by Elm results in `TypeError: domNode is undefined` JS error.

You can see [relevant Elm code here](https://github.com/lzrski/elm-onsen-playground/blob/c7678d05020bd3cc8ee917372f422414769c7013/src/Main.elm#L53-L67).

**Comment by lzrski** [comment] 2017-11-23 16:09
Unfortunately shadow DOM still seems not to be widely supported: https://caniuse.com/#search=shadow%20dom
