### ISSUE TITLE
White Blank Screen after Splash Screen 

### ISSUE THREAD

**Issue by wishbooks** [OnsenUI/OnsenUI#1363] opened 2016-04-14 07:19 UTC
__Environment__
Onsen 2 beta
Angular 1.4.3
iOS 9.3
Cordova iOS - 4.0.1
Cordova cli - 6.1.1

__Encountered problem__
Some times white screen (plain index.html) page is coming. Ons.ready event is also not firing in this case. 

__How to reproduce__
With this environment this issue always occuring

**Comment by argelius** [comment] 2016-04-22 06:22
Thanks for reporting @wishbooks ! Do you get any errors in the console?

**Comment by wishbooks** [comment] 2016-04-22 06:45
No. Errors are coming.

**Comment by argelius** [comment] 2016-07-11 09:20
I will close this since we are unable to reproduce it.

**Closed by argelius** 2016-07-11 09:20 UTC
