### ISSUE TITLE
ons-pull-hook bugs

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#449] opened 2015-02-16 15:36 UTC
Dear @argelius ,

thanks for your ons-pull-hook. I really tried hard, but there is no usecase where I could integrate this neat function into my app. No chance. I guess it is quite useless when it does not support  `<ons-scroller>`

I need to place content inside of my ons-scroller when my content is long. If I don't place it inside of ons-scroller (with a height) I can't scroll nothing on iOS. Or at least I can't set content (like an input) to be fixed at bottom.

I've made a 3-4 minute video to demonstrate what I mean. It's hard to describe the problem as a non-native-speaker.

**Comment by Hirbod** [comment] 2015-02-16 16:27
Here we go. Text inside of video
https://www.youtube.com/watch?v=9A0DXaf_IQg

**Comment by argelius** [comment] 2015-02-17 05:13
Thanks for the video @Hirbod!

I'll take a look at and see if I can reproduce it.

Is it possible for you to maybe make an example that fails? It would be nice to see if it fails on other platforms than Mobile Safari and what might cause it. Looks like the drag event is interrupted in some way.

Here is a simple example using ons-pull-hook if you'd like to fork it.
http://codepen.io/andipavllo/pen/jEZrdr

**Comment by argelius** [comment] 2015-02-17 06:13
By the way, I see no reason why `<ons-pull-hook>` should not be used with `<ons-scroller>` so I changed it to allow both tags:

https://github.com/OnsenUI/OnsenUI/commit/a0f31c2dbc6dfc743a8a566e9813da70dcceaf0c

**Comment by Hirbod** [comment] 2015-02-17 08:06
Hi @argelius,

I'll try it and I will try to make an example for you that fails.

**Comment by andipavllo** [comment] 2015-10-19 16:01
fixed in #965

**Comment by asial-matagawa** [comment] 2016-12-06 04:09
This issue seems to have been solved in #967. Closing this.

**Closed by asial-matagawa** 2016-12-06 04:09 UTC
