### ISSUE TITLE
Input type number not working in AngularJS

### ISSUE THREAD

**Issue by nickpdiana** [OnsenUI/OnsenUI#1827] opened 2017-02-17 23:09 UTC
__Environment__ 

```
[Core]
    Onsen UI 2.1.0

[Framework]
    Angular 1.5.9

[Framework binding]
    angular-onsenui 2.1.0

[Additional libraries]
    jQuery 3.1.1

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome 55.0.2883.75
```

__Encountered problem__
ons-input elements of type number do not retain that type

__How to reproduce__

I've attached a screenshot showing the issue. In the console, we see that ct.moneyInBank is initialized as a number, but once I edit the value in the ons-input box, it is converted to a string.

Here is the relevant code:
`<ons-input placeholder="Money in the Bank" type="number" float ng-model="ct.moneyInBank" ng-change="ct.drawLine()"></p>`

Here is a screenshot:
<img width="911" alt="screen shot 2017-02-17 at 6 01 26 pm" src="https://cloud.githubusercontent.com/assets/2049108/23086592/dfdb9950-f53b-11e6-8cdb-ac6bf54f308f.png">

**Comment by misterjunio** [comment] 2017-02-20 07:43
@nickpdiana We treat inputs different than radio buttons, checkboxes, selects and ranges as text inputs. Is there a specific reason why you need the type of the variable to be `number`?

**Comment by nickpdiana** [comment] 2017-02-20 17:56
Just for the same reasons why [vanilla input tags](http://w3c.github.io/html-reference/input.number.html) have a type number:

1) I don't have to cast the variable to an integer anytime I use it.
2) Mobile users are given a number pad for input instead of a keyboard.

My current solution is to just use a vanilla input tag styled with onsen classes, but that's not ideal.

**Comment by misterjunio** [comment] 2017-02-21 01:19
I think you may be a bit confused about what the input type number means because even a vanilla input will give you a string variable. From the link you posted:

> type = "number"
Specifies that its input element is a precise control for setting the **element’s value to a string representing a number**.

You can also try to log the `typeof` the element's value and it should give you `string`.
About the second point I'm not sure I am able to reproduce because both with and without `ons-` I get the keyboard but on the numbers and symbols pad which is the expected behavior.

**Comment by nickpdiana** [comment] 2017-02-21 02:12
Because of the data-binding in angular, the value for input[number] elements must be of type number. Here's a [jsbin](https://jsbin.com/mucewutuvu/edit?html,js,console,output).

If you edit the input, you'll see that the type remains a number. This is not true for `<ons-input>`. I'm aware that onsen is framework agnostic, I just wanted make sure you guys are aware that this isn't the expected behavior for input[number] elements in angular.

**Comment by misterjunio** [comment] 2017-02-21 03:07
You're right, I just fixed it and it should be merged soon 😃  Thank you.

**Closed** 2017-02-21 07:47 UTC
Labels: angular1, in progress
