### ISSUE TITLE
Uncaught SyntaxError: Unexpected token s (index):1

### ISSUE THREAD

**Issue by OpenNoob** [OnsenUI/OnsenUI#588] opened 2015-04-08 13:23 UTC
I tested the latest master-detail template using 1.3.0 build and everytime a list item is clicked/goes to another page/detail the console error "Uncaught SyntaxError: Unexpected token s (index):1 logs.

Is this causing something problematic? How to fix this?

Thanks.

**Comment by argelius** [comment] 2015-04-08 13:26
Thanks! I'll take a look at this.

**Comment by argelius** [comment] 2015-04-09 02:11
Actually I was unable to reproduce this. The template on the website works fine without errors when I tried it.

What device / browser are you running? Where did you download the template?

**Comment by OpenNoob** [comment] 2015-04-09 05:05
I downloaded it from here: http://onsen.io/OnsenUI/project_templates/onsen_master_detail.zip

on this page: http://onsen.io/download.html#download-templates

I just redownloaded it, run via local webserver and opened in Chrome Version 41.0.2272.118 (64-bit). Same error.

**Comment by argelius** [comment] 2015-04-09 05:07
Thanks @OpenNoob ! I will try it again.

**Comment by argelius** [comment] 2015-04-09 06:53
@OpenNoob 
I'm using the same Chrome version but I don't get the error. Could you paste the complete stack trace?

**Comment by OpenNoob** [comment] 2015-04-09 13:33
Hi argelius.

Unfortunately, there's not much else to report. See attached screenshot.

![screen shot 2015-04-09 at 9 32 02 pm](https://cloud.githubusercontent.com/assets/7935033/7067707/056d97d0-df00-11e4-8e8a-a8baa85c213f.png)

**Comment by argelius** [comment] 2015-04-10 02:48
Thanks @OpenNoob !

That's strange. Could you also please click the `(index):1` and paste what it says?

**Comment by OpenNoob** [comment] 2015-04-10 04:51
Here you go:
![screen shot 2015-04-10 at 12 48 29 pm](https://cloud.githubusercontent.com/assets/7935033/7082073/320983fa-df80-11e4-8afc-8432b1080942.png)

Note that this only happens in Chrome Dev tools. In Firefox inspector and Firebug, the error doesn't log.

**Comment by argelius** [comment] 2015-04-10 04:57
That's strange. I don't think it has anything to do with Onsen UI though so I'm closing this. Please open it again if you think otherwise.

**Closed by argelius** 2015-04-10 04:57 UTC
Labels: bug
