### ISSUE TITLE
ons-navigator and  OnsenUI 2.0 problem

### ISSUE THREAD

**Issue by zkorp** [OnsenUI/OnsenUI#1154] opened 2016-01-01 19:57 UTC
When I use ons-navigator and ons-toolbar I have a space above the tittle. Here is the image with ons-navigator.
![with-ons-navigator](https://cloud.githubusercontent.com/assets/16511196/12071972/43ae6426-b0c8-11e5-9ec4-01565138a2f7.jpg)

If I don't use ons-navigator the result is this:

![without-ons-navigator](https://cloud.githubusercontent.com/assets/16511196/12071973/43aeab3e-b0c8-11e5-87bf-7a7e4c0ba9ca.jpg)

This is the source code:
```
<ons-navigator animation="slide" var="app.navi">
 <ons-page modifier="material">
 
     <ons-toolbar modifier="material" class="careinterface">
    	 <div class="center">Log In</div>
     </ons-toolbar>

	<div class="login-form">
	  <p>
    <ons-material-input label="Username" id="username"></ons-material-input>
  	 </p>
     <p>
   <ons-material-input type="password" label="Password" id="password"></ons-material-input>
  	</p>
   
    <ons-button modifier="material" class="careinterface"style='width: 90px; display: inline-block; margin-bottom: 20px;' >
    	<ons-ripple></ons-ripple>
    	Login
  	</ons-button>
    
    <ons-button modifier="material" class="careinterface" style='width: 90px; margin-left: 15px; margin-bottom: 20px; display: inline-block;'>
    	<ons-ripple></ons-ripple>
    	Reset
  	</ons-button> 
  
 	<br>
    
    <ons-button modifier="material" class="careinterface" style='width: 200px; display: inline-block;' onclick="codigorfid()">
    	<ons-ripple></ons-ripple>
    	NFC Login
  </ons-button>
  
  </div>
 </ons-page>
</ons-navigator>
```
The ons-navigator functions work perfectly.

Thank you for your great work, I have used the 1.X version and now I am using the 2.0 versions and both are really good.

Regards

**Comment by argelius** [comment] 2016-01-05 03:10
Thanks @zkorp! I will investigate this.

**Comment by argelius** [comment] 2016-01-05 03:51
@zkorp I ran your code but couldn't reproduce the bug.

How are you running the app? Are you running it in a browser or as a hybrid app? What Android/iOS version are you running?

**Comment by zkorp** [comment] 2016-01-05 06:43
I am using Google Chrome v. 47.0.2526.106m under Windows 8. It only happens in Dev mode (F12) simulating a iPhone 5 and does not happen in normal mode.

The first time I load the web the problem will not appear but if I reload or navigate to other web inside the application the problem appears.

In Android 5.1 this problem does not appear.

Attach the full image with the Chrome un dev mode.

In the first image with the problem, the height is 76px defined by .page_status-bar-fill + ons-toolbar (onsenui.css: 81)

![screen_with_problem](https://cloud.githubusercontent.com/assets/16511196/12109054/867ae5c8-b37e-11e5-973f-e55bb2086056.jpg)

In the second image this CSS element is not affecting the code, the height is 56px and it is defined by .navegation-bar--material (onsen-css-components-blue-basic-theme.css)

![screen-withoutproblem](https://cloud.githubusercontent.com/assets/16511196/12109060/8e77e276-b37e-11e5-8dc0-121ce09e4665.jpg)

If  I change this values in the CSS files and the height of the bar will change.

I have other App with ONSEN UI 1.X and this problem does not appear.

Thanks @zkorp.

**Comment by argelius** [comment] 2016-01-06 02:46
@zkorp That's super strange. I'd really like to debug this but I need your help.

Can you write the following in the console when the bug has happened?

```
console.log(ons._internal.isEnabledAutoStatusBarFill(), ons.platform.isWebView(), ons.platform.isIOS7above())
```

What is the output? 

Can you also check if the `window.cordova` variable is defined?

**Comment by zkorp** [comment] 2016-01-06 08:32
@argelius thank for your help. I will help all I can.

About the code in the console:

![console_output_with_bug](https://cloud.githubusercontent.com/assets/16511196/12137627/94524c3e-b452-11e5-824b-f3138db8743e.jpg)

The output is the same with and without the error.

About window.cordova

![window cordova](https://cloud.githubusercontent.com/assets/16511196/12137998/9b7bfd5e-b455-11e5-9fd6-c84c82d7da2f.jpg)

I have tried without cordova, only for a web using ONSEN and it works fine. If I load cordova I have the problems but with Cordova if I export to Android App it works fine too. 

I don't know the reason for this problem but I think it is only a problem for debugging the developers because the final App or website works fine.

Thanks @argelius

**Comment by argelius** [comment] 2016-01-06 10:41
Thanks @zkorp !

I think this is only an issue when you emulate iPhone in Chrome. I will close it but feel free to open it again if you feel it needs to be fixed.

**Closed by argelius** 2016-01-06 10:41 UTC
Labels: bug
