### ISSUE TITLE
bad topPage.name after popPage

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1434] opened 2016-05-26 15:39 UTC
__Environment__
Onsen 2 rc 6
Angular 

__Encountered problem__
I have some problems with pages' stack and its parameters while using pushPage / popPage. 
It seems that popPage doesn't update nav.topPage while entering into the new page. 

Example
------------

### pushPage 1 
this.myNavigator.pushPage('view-mypage.html', {data : {selectedParam:myObj}, animation: "none"});
=> log: MyController::constructor(): topPage.name='view-mypage.html' with custom data: MyObject {...}

### pushPage 2
this.myNavigator.pushPage('new-mypage2.html', {data : {selectedParam:myObj2}, animation: "none"});
=> log: MyController2::constructor(): topPage.name='new-mypage2.html' with custom data: MyObject2 {...}

### popPage (refresh=true)
this.myNavigator.popPage({refresh:true});
=> log: MyController::constructor(): topPage.name='new-mypage2.html' with custom data: MyObject2 {...} 
instead of: topPage.name='view-mypage.html' and MyObject

I don't know if it's a bug or an misuse from my part ?
Why is it not possible to pass 'data' parameter with popPage ? It would be easier in some cases to manage custom datas.

**Comment by frankdiox** [comment] 2016-05-26 16:05
@bdedardel Hello! I would understand this error for rc.5, but I think this should be fixed in rc.6. I cannot see any problem with `{refresh: true}`: https://codepen.io/frankdiox/pen/wWwYog?editors=101

We'll probably add `data` for `popPage` as well.

**Comment by bdedardel** [comment] 2016-05-27 06:04
Hi @frankdiox 
I use rc6. To reproduce, just add in your example: 

```
myNavigator.addEventListener('init', function(event) {
		alert(myNavigator.topPage.name);
```
I you popPage from page3.html to page2.html, it will show 'page3.html' instead of 'page2.html'.
topPage was, in the last versions currentPage. That's why I expect this behaviour.
It makes sense for me !

**Comment by frankdiox** [comment] 2016-05-30 11:35
@bdedardel Yes, I modified the example and saw it. It's weird, I'll take a look and see why that happens. Anyway, you are getting an `event` object that has the real page as `event.target`, so maybe you can use that instead for now.

**Comment by IliaSky** [comment] 2016-05-31 05:55
@frankdiox I looked into it - It seems that at the time we were using `getCurrentPage` we were still keeping an internal `_pages` stack and managing it manually. So we were calling `_pages.pop()` in `_popPage`, whereas right now we're just using the actual children. Knowing that fact right now the current behaviour is logical as during the `init` event of the refreshed page the other page is still inside the dom. I'm not really sure whether we want to go back to manually managing that stack though. I guess we should think about it. Otherwise if we want to patch this it may be a little ugly (similar issues may arise with `resetToPage` and `replacePage`).

@bdedardel Since the `init` event is for the initialisation of the page it happens before the popPage animation starts (and it's natural for the `topPage` to point at the top page, which is still `page3`), so we're not sure if we should consider this a bug or expected behaviour. If you want to do something when the page is shown instead of initialised you should use the `show` event. That event is called after the animations, so feel free to use that for the time being or if we decide not to change this behaviour. (or `event.target` as @frankdiox suggested)

**Comment by bdedardel** [comment] 2016-05-31 09:14
@IliaSky 
I think that it could not be considered as an expected behaviour, because 
- if your enter in page2 with a pushPage, topPage will be 'page2.html'
- but if your enter in page2 with a popPage, topPage will be 'page3.html'
It is not logic!

Thanks for the other solution, I will study it. But as I use typescript + angular with controllers, I need this info inside my constructor.

**Comment by frankdiox** [comment] 2016-05-31 09:35
@IliaSky Thanks for looking at it! Yes, I imagined it was related to the DOM not being ready. I would also say that this is kind of normal behavior because `init` event is not related to `ons-navigator`, but to `ons-page`, and thus it has no idea about `navi.topPage` or anything else. 
To be more specific, `init` event is fired when the page is attached to the DOM. The difference between the 2 cases you mention, @bdedardel , is that `pushPage` attaches the new page directly at the top but `popPage` with `refresh` needs to attach the refreshed page before the top page.
@bdedardel As we mentioned before, you are getting the page object as `event.target` in the page's `init` event and that's the normal way to use it. If you want to use `navi.topPage` for some reason then you need to use navigator's `postpop` event or page's `show` event, although those are not the best place to initialize a page.

**Comment by bdedardel** [comment] 2016-06-05 15:38
For those who need to have the current page name in the constructor of controllers, before the init event, I use my own Navigator to pop/push pages :

html
``` 
<ons-template id="page1.html">
	<ons-page ng-controller="MyController1 as myCtl1" id="mypage1">		
		...	
	</ons-page>
</ons-template>
```
typescript
``` 
module myModule {
    'use strict';

    export class MyNavigator {
       	
     	public static onsNavigator: any = null;
    	public static isPopAction: boolean = false;
    	
    	public static pushPage(page:string,param:any): void {
    		Navigator.isPopAction = false;
    		Navigator.onsNavigator.pushPage(page, {data : {selectedParam:param}, animation: "none"});	
    	}

    	public static popPage(refresh:boolean): void {
    		Navigator.isPopAction = true;
    		if (refresh) {
    			Navigator.onsNavigator.popPage({refresh:true});
    		} else {
    			Navigator.onsNavigator.popPage();
    		}	
    	}

    	public static getCurrentPage(): any {
    		if (Navigator.isPopAction) {
     			return Navigator.onsNavigator.pages[Navigator.onsNavigator.pages.length-2];
    		} else {
    			return Navigator.onsNavigator.topPage;
    		}
    	}		
     }
}
```
javascript
``` 
document.addEventListener("pageinit", function(e) {
  myModule.myNavigator.isPopAction = false; 
  ...
}
```

**Closed** 2016-06-06 09:46 UTC
