### ISSUE TITLE
sliding-menu issue while on landscape 

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#442] opened 2015-02-11 07:22 UTC
On portrait mode the sliding menu is closing if you tap outside the menu page (normal), the same does not happen if the orientation is landscape.The only way to close it is to force the user 
to select an item from the list on the menu page.

**Comment by argelius** [comment] 2015-02-12 02:20
Thanks @JcDenton86 

Are you using iOS or Android? Please tell me what device you're using and what OS version.

**Comment by JcDenton86** [comment] 2015-02-12 07:18
Hi @argelius ,
I forgot to mention that. I am using Android 5 and it's on my nexus 5.

**Comment by argelius** [comment] 2015-02-17 06:47
I was unable to reproduce this on Android 5 running on a Nexus 7.

Could you please provide some code that reproduces this issue? Closing this in the meanwhile.

**Closed by argelius** 2015-02-17 06:47 UTC

**Comment by JcDenton86** [comment] 2015-02-17 07:55
Hi,
I used the latest files from the repository and the issue didn't happen again..
Thank you
