### ISSUE TITLE
BUG: Application broken after latest updates + CSS Path are wrong and hence does not compile project

### ISSUE THREAD

**Issue by vishal-shukla-viitorcloud** [OnsenUI/OnsenUI#2988] opened 2022-06-18 05:40 UTC
Reporting a bug
================
Our application using below version since long and suddenly its broken without any changes to application
**"onsenui": "^2.10.4"**

Found that it suddenly broke the application recently

**Onsen UI Version:**
- 2.10.4

**Framework:**
- JavaScript

**Additional libraries:**
- jQuery 3.3.1
- Webpack 4.46.0

**Platform:**
- Chrome

**__Encountered problem__**
- Page navigation stopped working because of JavaScript error, it should work normally as there is no code changes from application level

**Attached issue:** 
1. Application issue after using fixed version 2.10.4 as got issue with 2.12.X

![image](https://user-images.githubusercontent.com/77824464/174424136-c50e42ee-2b5e-4953-89f7-a4848e5b445f.png)

![image](https://user-images.githubusercontent.com/77824464/174424180-3ab351df-1811-48a2-8039-11f80e0e833a.png)

2. Correct path with 2.10.4

![image](https://user-images.githubusercontent.com/77824464/174424310-24e49092-a104-47f3-a2f9-b84c57eff8b6.png)

Wrong path with ^2.10.4 (So giving babel loader issue while build)

![image](https://user-images.githubusercontent.com/77824464/174424553-37f51aae-bd51-4d52-b972-4cf408f04d44.png)

Please help asap.
Thanks.

**Comment by emccorson** [comment] 2022-06-21 03:17
Firstly, Onsen UI has breaking changes between minor versions (e.g. 2.11 -> 2.12), so I would recommend using `~` instead of `^` in your package.json to stop thing suddenly breaking.

Concerning the CSS, I checked onsenui.css in the latest Onsen UI (2.12.0) and the CSS imports seem fine:
```
@import url("./ionicons/css/ionicons.min.css");
@import url("./material-design-iconic-font/css/material-design-iconic-font.min.css");
@import url("./font_awesome/css/all.min.css");
@import url("./font_awesome/css/v4-shims.min.css");
```

If you can provide a minimal code sample to reproduce the problem, I can look into it, but at the moment there is not enough information in this report to reproduce the problem.

**Comment by emccorson** [comment] 2022-08-31 09:44
Closing as can't reproduce.

**Closed by emccorson** 2022-08-31 09:44 UTC
